### ISSUE TITLE
 BetterRespawn is built for Minecraft 1.19.4 ?

### ISSUE THREAD

**Issue by Ellen7ions** [MineDojo/Voyager#10]
I find better respawn mod is built for 1.19.4 which is not compatible with frabic for 1.19.

**Comment by Anonym0us33** [comment]
this project doesn't seem compatible with that version. see if you can find a combination of mods that works and mention it here. But it looks like you need to compile it as per instructions here because its not compatible with the compiled releases available online.

**Comment by Ellen7ions** [comment]
Thanks. do u konw how to complie this fabric mod for 1.19 ?

**Comment by Anonym0us33** [comment]
no I just followed the instructions

**Comment by xieleo5** [comment]
Hi, all. Thanks for your interest in this project! The fabric installation tutorial has a link to a forked version of `better-respawn`. You need to clone that one and manually compile it. In case you don't notice it, here is the link: [Better-Respawn](https://github.com/xieleo5/better-respawn/tree/1.19)

**Comment by bagusindrayana** [comment]
> Thanks. do u konw how to complie this fabric mod for 1.19 ?

check the branch name, if you clone with git command try this `git clone --branch 1.19 https://github.com/xieleo5/better-respawn.git`

**Comment by go-maple** [comment]
@bagusindrayana 
bro,help me.
I used the command "git clone --branch 1.19 https://github.com/xieleo5/better-respawn.git"
this is my envirement
<img width="579" alt="image" src="https://github.com/MineDojo/Voyager/assets/97354215/b3892b07-df47-4e66-b16a-1d3ccd746283">
the error
<img width="938" alt="image" src="https://github.com/MineDojo/Voyager/assets/97354215/9bac02ab-83ca-4292-bd7b-9937ce7f823a">
I use the command "gradle build" to build the porject.

**Comment by go-maple** [comment]
@bagusindrayana 
It’s my fault
step1:
git clone --branch 1.19 https://github.com/xieleo5/better-respawn.git
step2:
cd better-respawn && chmod +x gradlew  
step3:
./gradlew build or ./gradlew build --stacktrace(option)

<img width="337" alt="image" src="https://github.com/MineDojo/Voyager/assets/97354215/35d8a6d5-8069-4708-8faf-50f844497e6f">

**Comment by GoingMyWay** [comment]
> > Thanks. do u konw how to complie this fabric mod for 1.19 ?
> 
> check the branch name, if you clone with git command try this `git clone --branch 1.19 https://github.com/xieleo5/better-respawn.git`

Really helps!
