### ISSUE TITLE
Could another agent be embodied in the environment?

### ISSUE THREAD

**Issue by ReinholdM** [MineDojo/Voyager#102]
Hi, 

Thanks for this very cool work! And I have a question about the customized environment or task. If another agent is controlled by LLMs or other neural networks, is it feasible in this framework?

**Comment by GoingMyWay** [comment]
Do you mean there are multiple agents in the environment?

**Comment by ReinholdM** [comment]
> Do you mean there are multiple agents in the environment?

Yes, exactly.

**Comment by GoingMyWay** [comment]
> > Do you mean there are multiple agents in the environment?
> 
> Yes, exactly.

I think it can. You can create many bots via using MineFlayer.
