### ISSUE TITLE
Linux version of Minecraft

### ISSUE THREAD

**Issue by dongyh20** [MineDojo/Voyager#104]
I've tried to run the code on the linux server. However, I failed to install the linux version of Minecraft. Is there any useful guidance?

**Comment by GoingMyWay** [comment]
You can run the Minecraft server (without GUI) on linux servers. You can follow the following steps: https://github.com/MineDojo/Voyager/pull/100

**Comment by dongyh20** [comment]
[#100](https://github.com/MineDojo/Voyager/pull/100) works for me! Thanks a lot!
