### ISSUE TITLE
Feedback from humans

### ISSUE THREAD

**Issue by doxav** [MineDojo/Voyager#108]
According to your paper, you used human feedback in Voyager to achieve new tasks like complex 3D structures.

How to reproduce the experiment ? Test both human as a critic and human as a curriculum ?

**Comment by doxav** [comment]
@xieleo5 @theblazehen are the human feedback (mentioned in paper) in the github repo cause I could not find it ?

**Comment by xieleo5** [comment]
Hi, sorry for the late reply. I've been busy these days. For human in-loop experiments, you can follow this way to instantiate voyager:
```python
voyager = Voyager(
    ...
    reset_placed_if_failed=True,
    action_agent_task_max_retries=100,
    action_agent_show_chat_log=False,
    curriculum_agent_mode="manual",
    critic_agent_mode="manual",
    ...
)
```
You will be asked to give the next task and judge whether the task is finished.
