### ISSUE TITLE
Mulit-agent Voyager

### ISSUE THREAD

**Issue by JulianYocum** [MineDojo/Voyager#111]
I'm interested in having multiple voyager bots interacting in the same world. How feasible/difficult would this be to do?

**Comment by Resurgamm** [comment]
> I'm interested in having multiple voyager bots interacting in the same world. How feasible/difficult would this be to do?

Have you solved the problem? If so, could you please give me a copy of the code for reference.

**Comment by JulianYocum** [comment]
Turns out this is possible. You just have to make sure the bots are on different mineflayer ports. I do so [here](https://github.com/JulianYocum/Voyager-Contracting).
