### ISSUE TITLE
error when using npx-tsc in mineflayer-collectblock folder

### ISSUE THREAD

**Issue by Toisoi** [MineDojo/Voyager#112]
python 3.10.6
nodejs 20.4.0

When trying use `npx tsc` in mineflayer-collectblock folder i get this error

```
src/BlockVeins.ts:2:10 - error TS2305: Module '"prismarine-block"' has no exported member 'Block'.

2 import { Block } from 'prismarine-block'
           ~~~~~

src/CollectBlock.ts:2:10 - error TS2305: Module '"prismarine-block"' has no exported member 'Block'.

2 import { Block } from "prismarine-block";
           ~~~~~

src/CollectBlock.ts:186:9 - error TS2578: Unused '@ts-expect-error' directive.

186         // @ts-expect-error
            ~~~~~~~~~~~~~~~~~~~

src/Targets.ts:2:10 - error TS2305: Module '"prismarine-block"' has no exported member 'Block'.

2 import { Block } from 'prismarine-block'
```

**Comment by oserikov** [comment]
Same thing on my side. Mac OS 13.2.1 M1Pro

**Comment by oserikov** [comment]
@Toisoi seems that I've managed to fix this for me by replacing `"prismarine-block": "^1.16.3"` with `"prismarine-block": "=1.16.3"` in package.json (Voyager/voyager/env/mineflayer/package.json)

**Comment by ChrisBrink078** [comment]
Sorry but i am still having issues (Debian 12). this is the error message:

npx tsc                    
src/BlockVeins.ts:2:10 - error TS2305: Module '"prismarine-block"' has no exported member 'Block'.
2 import { Block } from 'prismarine-block'
src/CollectBlock.ts:2:10 - error TS2305: Module '"prismarine-block"' has no exported member 'Block'.
2 import { Block } from "prismarine-block";
src/CollectBlock.ts:186:9 - error TS2578: Unused '@ts-expect-error' directive.
186         // @ts-expect-error
src/Targets.ts:2:10 - error TS2305: Module '"prismarine-block"' has no exported member 'Block'.
2 import { Block } from 'prismarine-block'
Found 4 errors in 3 files.
Errors  Files
     1  src/BlockVeins.ts:2
     2  src/CollectBlock.ts:2
     1  src/Targets.ts:2

**Comment by ImJohnDoe** [comment]
Thanks for the fix @oserikov, I'm submitting a pr with this change.

**Comment by xieleo5** [comment]
Hi, thanks for pointing out this! PR is merged.
