### ISSUE TITLE
AzureAppNotPermitted on new installs.

### ISSUE THREAD

**Issue by escozul** [MineDojo/Voyager#119]
### Briefly describe your issue
When creating a new app, and using Web as type (desktop / mobile didn't work. Got access.token error) I still got the error:
AzureAppNotPermitted.
### Please provide your python, nodejs, Minecraft, and Fabric versions here
All versions are ok. It's not an issue that is unsolvable.
### [If applicable] Please provide the Minefalyer and Minecraft logs, you can find the log under `logs` folder
No logs required.
### [If applicable] Please provide the GPT conversations that are printed each round.
Not required

The problem is not covered in the documentation or the FAQ and should be added.
It seems that it's a new Mojang/microsoft policy to have all apps request access to the minecraft API before use.  (https://help.minecraft.net/hc/en-us/articles/16254801392141p)
So the first time the app is run, it will pop up this error. [AzureAppNotPermitted]
`minecraft_launcher_lib.exceptions.AzureAppNotPermitted: It looks like your Azure App don't have the Permission to use the Minecraft API. Take a look at the Documentation for more Information.`
The user needs to fill in this form: https://aka.ms/mce-reviewappid

more info here: https://minecraft-launcher-lib.readthedocs.io/en/stable/tutorial/microsoft_login.html#apply-for-permission

**Comment by xieleo5** [comment]
Hi, @escozul. Thanks for reporting that. I think this is a new requirement from the Microsoft side. Did you get the permission now?

**Comment by yuymf** [comment]
Hi@escozul, the same error i met and i just submitted the form, can i know if you get in or how long it takes to get the approval , thank you!!!

**Comment by nick-casa** [comment]
> Hi@escozul, the same error i met and i just submitted the form, can i know if you get in or how long it takes to get the approval , thank you!!!

Do you have approval yet?

**Comment by bicro** [comment]
Anyone been able to get approval or get past this issue?

**Comment by adamhalama** [comment]
I just got the same error: 
`minecraft_launcher_lib.exceptions.AzureAppNotPermitted: It looks like your Azure App don't have the Permission to use the Minecraft API. Take a look at the Documentation for more Information.`

Anyone has gotten closer to solving this?

**Comment by pj0620** [comment]
I just submitted to the form. Hoping others got a response on it.
