### ISSUE TITLE
Cannot set up Voyager: system environment issue

### ISSUE THREAD

**Issue by Coppelian** [MineDojo/Voyager#127]
### Before submitting an issue, make sure you read the [FAQ.md](FAQ.md)
Yes, I've read the FAQ session and find no solution.

### Briefly describe your issue
I faced a problem when I tried to set up Voyager on Windows 10.
I'm using Conda Python 9 with Nodejs 18.18.0 LTS to set up this program following the readme file.
When it comes to command `npx tsc`, I faced an error and I'm having trouble to solve it.
The log is demonstrated here:
```
(python39) PS C:\Github_program\Voyager\voyager\env\mineflayer\mineflayer-collectblock> npx tsc
src/BlockVeins.ts:25:32 - error TS2345: Argument of type 'import("C:/Github_program/Voyager/voyager/env/mineflayer/node_modules/mineflayer/node_modules/prismarine-block/index").Block' is not assignable to parameter of type 'import("C:/Github_program/Voyager/voyager/env/mineflayer/node_modules/prismarine-block/index").Block'.
  The types returned by 'getProperties()' are incompatible between these types.
    Type '{ [key: string]: string | number | boolean; }' is not assignable to type '{ [key: string]: string | number; }'.
      'string' index signatures are incompatible.
        Type 'string | number | boolean' is not assignable to type 'string | number'.
          Type 'boolean' is not assignable to type 'string | number'.

25           if (targets.includes(neighbor)) continue
                                  ~~~~~~~~

src/BlockVeins.ts:26:29 - error TS2345: Argument of type 'import("C:/Github_program/Voyager/voyager/env/mineflayer/node_modules/mineflayer/node_modules/prismarine-block/index").Block' is not assignable to parameter of type 'import("C:/Github_program/Voyager/voyager/env/mineflayer/node_modules/prismarine-block/index").Block'.

26           if (open.includes(neighbor)) continue
                               ~~~~~~~~

src/BlockVeins.ts:28:21 - error TS2345: Argument of type 'import("C:/Github_program/Voyager/voyager/env/mineflayer/node_modules/mineflayer/node_modules/prismarine-block/index").Block' is not assignable to parameter of type 'import("C:/Github_program/Voyager/voyager/env/mineflayer/node_modules/prismarine-block/index").Block'.

28           open.push(neighbor)
                       ~~~~~~~~

src/CollectBlock.ts:209:23 - error TS2345: Argument of type 'import("C:/Github_program/Voyager/voyager/env/mineflayer/node_modules/prismarine-block/index").Block' is not assignable to parameter of type 'import("C:/Github_program/Voyager/voyager/env/mineflayer/node_modules/mineflayer/node_modules/prismarine-block/index").Block'.
  Type 'Block' is missing the following properties from type 'Block': setSignText, getSignText

209         await bot.dig(block);
                          ~~~~~


Found 4 errors in 2 files.

Errors  Files
     3  src/BlockVeins.ts:25
     1  src/CollectBlock.ts:209
```
We tested this in both Windows 10 and Ubuntu 22 LTS, the same error occured.
We think this could be an error with Nodejs version, or an error with npx.
Could you please share your system setup details here? With the versions you used to deploy Voyager? Thank you.

...
### Please provide your python, nodejs, Minecraft, and Fabric versions here
Python 9
Nodejs 18.18.0 LTS
Windows 10/ Ubuntu22 LTS
Minecraft and Fabric not setup yet.(Is there something to do with this?) 

...
### [If applicable] Please provide the Minefalyer and Minecraft logs, you can find the log under `logs` folder
...
N/A
### [If applicable] Please provide the GPT conversations that are printed each round.
...
N/A

Thank you for reviewing this issue. If it's possible please contact coppelia@yorku.ca
I appreciate all your help and support!

**Comment by lincvic** [comment]
Same issue, May caused by package conflict.

Try to delete `prismarine-block` in  `../Voyager/voyager/env/mineflayer/node_modules/mineflayer/node_modules/prismarine-block`

**Comment by Coppelian** [comment]
Thanks for your advice!@lincvic
