### ISSUE TITLE
Is it possible to give a approximate cost for each run? Want to try it but have a budget limit 

### ISSUE THREAD

**Issue by mixuechu** [MineDojo/Voyager#128]
### Briefly describe your issue
...
### Please provide your python, nodejs, Minecraft, and Fabric versions here
...
### [If applicable] Please provide the Minefalyer and Minecraft logs, you can find the log under `logs` folder
...
### [If applicable] Please provide the GPT conversations that are printed each round.
...

**Comment by xieleo5** [comment]
Hi, sorry for the late reply. The estimated cost of 160 iterations is around $30-$50. You can also check #4 for more information.
