### ISSUE TITLE
How to show the bot's first person perspective ?

### ISSUE THREAD

**Issue by Ellen7ions** [MineDojo/Voyager#13]

**Comment by xieleo5** [comment]
Hi, I just answered the same question in #19, you can check the answer there. Thanks for your interest!

**Comment by taoisu** [comment]
BTW, @Ellen7ions I'm using teleport to move myself to the bot to watch it from third-person perspective if that's helpful to you.

**Comment by changtimwu** [comment]
Sounds like a reasonable solution.  We're happy to take the role of "cameraman" for a gifted bot like Voyager. 😆 

> BTW, @Ellen7ions I'm using teleport to move myself to the bot to watch it from third-person perspective if that's helpful to you.
