### ISSUE TITLE
Can't run voyager.learn() for the first time: We're unable to complete your request, unauthorized_client

### ISSUE THREAD

**Issue by VincentCCandela** [MineDojo/Voyager#130]
OS: Ubuntu 22.04
Python: 3.10

After running trying to run the script under Getting Started section of the readme, I get the following terminal output:

![image](https://github.com/MineDojo/Voyager/assets/31104403/de4c8542-63b3-406a-9d89-b21685c7ca0e)

I opened the link in firefox and got the below results:

![image](https://github.com/MineDojo/Voyager/assets/31104403/488c94e0-a7ab-45c7-8342-44d4b62214c2)

I then copy and pasted the link "https://go.microsoft.com/fwlink/?linkid=2083908" into the terminal and the program terminated. 

Below is the entirety of the terminal output:

![image](https://github.com/MineDojo/Voyager/assets/31104403/7e9c954f-4ccd-42fc-aab1-1575232bfa01)

**Comment by VincentCCandela** [comment]
I think the next best option would be to manually register an Azure application, but I don't see any instructions on how to do that.

**Comment by VincentCCandela** [comment]
Was able to create an azure app registration. Should I change the redirect_url? What else do I need to do for a manual install?

![image](https://github.com/MineDojo/Voyager/assets/31104403/f5aa03f9-d00d-4394-8eed-8640d4145a8e)

**Comment by VincentCCandela** [comment]
I just used mc_port. It's so much simpler than Azure.

**Comment by egeozguroglu** [comment]
@xieleo5 Same issue as this.
