### ISSUE TITLE
How to configure the environment on top of MineDojo?

### ISSUE THREAD

**Issue by Aurora-1412** [MineDojo/Voyager#133]
### Before submitting an issue, make sure you read the [FAQ.md](FAQ.md)
I'm sure.
### Briefly describe your issue
As stated in the paper, the environment is built upon MineDojo, however, it seems that "MineDojo" isn't used when setting up environment in the GitHub repository and users have to download Minecraft.  Could you please tell me how to set up environment based on MineDojo?

...

**Comment by MurakamiNatsuki** [comment]
I am also interested in this issue.
I can't discern the relationship between MineDojo and Voyager from the code. I would appreciate it if someone could provide some explanation.
