### ISSUE TITLE
i can't start using voyager because i got error

### ISSUE THREAD

**Issue by Poseidon0901** [MineDojo/Voyager#136]
### Before submitting an issue, make sure you read the [FAQ.md](FAQ.md)
yes
### Briefly describe your issue
I am using 
(i hide my client_id, secret_value, openai_api_key)
```python
from voyager import Voyager

# You can also use mc_port instead of azure_login, but azure_login is highly recommended
azure_login = {
    "client_id": "client_id",
    "redirect_url": "https://127.0.0.1/auth-response",
    "secret_value": "secret_value",
    "version": "fabric-loader-0.14.18-1.19", # the version Voyager is tested on
}
openai_api_key = "api_key"

voyager = Voyager(
    azure_login=azure_login,
    openai_api_key=openai_api_key,
)

# start lifelong learning
voyager.learn()
``` 
i got this error:
```cmd
C:\Users\p0975\Documents\git\MinecraftAI\Voyager\voyager>python "minecraft ai.py"
Traceback (most recent call last):
  File "C:\Users\p0975\Documents\git\MinecraftAI\Voyager\voyager\minecraft ai.py", line 1, in <module>
    from voyager import Voyager
  File "C:\Users\p0975\Documents\git\MinecraftAI\Voyager\voyager\voyager.py", line 7, in <module>
    import voyager.utils as U
ModuleNotFoundError: No module named 'voyager.utils'; 'voyager' is not a package
``` 
### Please provide your python, nodejs, Minecraft, and Fabric versions here
Windows 10 64bit Professional 22H2 19045.3639
Python 3.9.0
Node.js 16.13.0
Minecraft Java 1.19
Fabric-loader-0.14.18-1.19
use git clone https://github.com/MineDojo/Voyager to clone Voyager
### [If applicable] Please provide the Minefalyer and Minecraft logs, you can find the log under `logs` folder
...
### [If applicable] Please provide the GPT conversations that are printed each round.
...

**Comment by air-balls** [comment]
Hello,have you solve the problem? I have met the same situation as you. There isn't voyager.utils in the repository right now while I have successfully ran the code a few months before.
