### ISSUE TITLE
Runtime Error; Minecraft Server replies with error code 400

### ISSUE THREAD

**Issue by Tostah** [MineDojo/Voyager#140]
Running Voyager on Ubuntu through oracle VM. Running the LAN server on my host machine. The port is open.
![Screenshot 2024-01-09 225011](https://github.com/MineDojo/Voyager/assets/64234012/14b33f44-bb38-4f55-b28c-112678aa052e)
![Screenshot 2024-01-09 224818](https://github.com/MineDojo/Voyager/assets/64234012/6e849e86-8321-4921-ad60-bb4bf531eed4)

I had an idea to change the IP from bridge.py from the loopback to the IP of the host machine, doing that puts it in an infinite loop untill it times out. 

A potential solution would be running the LAN server on the same VM that Voyager is running on, but not only is the VM on the same network as the LAN server, its on the same machine, using the same network adapter. 

Any help is much appreciated!

**Comment by uwFengyuan** [comment]
I have a similar problem. Have you solved your problem?
