### ISSUE TITLE
Error while installing 

### ISSUE THREAD

**Issue by igjnaj** [MineDojo/Voyager#143]
Microsoft Windows [Version 10.0.17763.3770]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Users\Administrator>cd desktop

C:\Users\Administrator\Desktop>cd asd

C:\Users\Administrator\Desktop\asd>git clone https://github.com/MineDojo/Voyager
fatal: destination path 'Voyager' already exists and is not an empty directory.

C:\Users\Administrator\Desktop\asd>cd Voyager

C:\Users\Administrator\Desktop\asd\Voyager>pip install -e .
Obtaining file:///C:/Users/Administrator/Desktop/asd/Voyager
  Preparing metadata (setup.py) ... done
Collecting tqdm
  Using cached tqdm-4.66.1-py3-none-any.whl (78 kB)
Collecting langchain
  Using cached langchain-0.1.0-py3-none-any.whl (797 kB)
Collecting javascript
  Using cached javascript-1%211.1.2-py3-none-any.whl (34 kB)
Requirement already satisfied: setuptools in c:\users\administrator\appdata\local\programs\python\python311\lib\site-packages (from voyager==0.1) (65.5.0)
Collecting openai
  Using cached openai-1.7.2-py3-none-any.whl (212 kB)
Collecting chardet
  Using cached chardet-5.2.0-py3-none-any.whl (199 kB)
Collecting cchardet
  Using cached cchardet-2.1.7.tar.gz (653 kB)
  Preparing metadata (setup.py) ... done
Collecting chromadb==0.3.29
  Using cached chromadb-0.3.29-py3-none-any.whl (396 kB)
Collecting tiktoken
  Using cached tiktoken-0.5.2-cp311-cp311-win_amd64.whl (786 kB)
Collecting requests
  Using cached requests-2.31.0-py3-none-any.whl (62 kB)
Collecting gymnasium
  Using cached gymnasium-0.29.1-py3-none-any.whl (953 kB)
Collecting psutil
  Using cached psutil-5.9.7-cp37-abi3-win_amd64.whl (252 kB)
Collecting minecraft_launcher_lib
  Using cached minecraft_launcher_lib-6.4-py3-none-any.whl (43 kB)
Collecting pandas>=1.3
  Using cached pandas-2.1.4-cp311-cp311-win_amd64.whl (10.6 MB)
Collecting pydantic<2.0,>=1.9
  Using cached pydantic-1.10.13-cp311-cp311-win_amd64.whl (2.1 MB)
Collecting hnswlib>=0.7
  Using cached hnswlib-0.8.0-cp311-cp311-win_amd64.whl
Collecting clickhouse-connect>=0.5.7
  Using cached clickhouse_connect-0.6.23-cp311-cp311-win_amd64.whl (229 kB)
Collecting duckdb>=0.7.1
  Using cached duckdb-0.9.2-cp311-cp311-win_amd64.whl (10.3 MB)
Collecting fastapi==0.85.1
  Using cached fastapi-0.85.1-py3-none-any.whl (55 kB)
Collecting uvicorn[standard]>=0.18.3
  Using cached uvicorn-0.25.0-py3-none-any.whl (60 kB)
Collecting numpy>=1.21.6
  Using cached numpy-1.26.3-cp311-cp311-win_amd64.whl (15.8 MB)
Collecting posthog>=2.4.0
  Using cached posthog-3.3.1-py2.py3-none-any.whl (40 kB)
Collecting typing-extensions>=4.5.0
  Using cached typing_extensions-4.9.0-py3-none-any.whl (32 kB)
Collecting pulsar-client>=3.1.0
  Using cached pulsar_client-3.4.0-cp311-cp311-win_amd64.whl (3.4 MB)
Collecting onnxruntime>=1.14.1
  Using cached onnxruntime-1.16.3-cp311-cp311-win_amd64.whl (7.4 MB)
Collecting tokenizers>=0.13.2
  Using cached tokenizers-0.15.0-cp311-none-win_amd64.whl (2.2 MB)
Collecting overrides>=7.3.1
  Using cached overrides-7.4.0-py3-none-any.whl (17 kB)
Collecting starlette==0.20.4
  Using cached starlette-0.20.4-py3-none-any.whl (63 kB)
Collecting anyio<5,>=3.4.0
  Using cached anyio-4.2.0-py3-none-any.whl (85 kB)
Collecting charset-normalizer<4,>=2
  Using cached charset_normalizer-3.3.2-cp311-cp311-win_amd64.whl (99 kB)
Collecting idna<4,>=2.5
  Using cached idna-3.6-py3-none-any.whl (61 kB)
Collecting urllib3<3,>=1.21.1
  Using cached urllib3-2.1.0-py3-none-any.whl (104 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2023.11.17-py3-none-any.whl (162 kB)
Collecting colorama
  Using cached colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Collecting cloudpickle>=1.2.0
  Using cached cloudpickle-3.0.0-py3-none-any.whl (20 kB)
Requirement already satisfied: farama-notifications>=0.0.1 in c:\users\administrator\appdata\local\programs\python\python311\lib\site-packages (from gymnasium->voyager==0.1) (0.0.4)
Collecting PyYAML>=5.3
  Using cached PyYAML-6.0.1-cp311-cp311-win_amd64.whl (144 kB)
Collecting SQLAlchemy<3,>=1.4
  Using cached SQLAlchemy-2.0.25-cp311-cp311-win_amd64.whl (2.1 MB)
Collecting aiohttp<4.0.0,>=3.8.3
  Using cached aiohttp-3.9.1-cp311-cp311-win_amd64.whl (364 kB)
Collecting dataclasses-json<0.7,>=0.5.7
  Using cached dataclasses_json-0.6.3-py3-none-any.whl (28 kB)
Collecting jsonpatch<2.0,>=1.33
  Using cached jsonpatch-1.33-py2.py3-none-any.whl (12 kB)
Collecting langchain-community<0.1,>=0.0.9
  Using cached langchain_community-0.0.12-py3-none-any.whl (1.6 MB)
Collecting langchain-core<0.2,>=0.1.7
  Using cached langchain_core-0.1.10-py3-none-any.whl (216 kB)
Collecting langsmith<0.1.0,>=0.0.77
  Using cached langsmith-0.0.80-py3-none-any.whl (48 kB)
Collecting tenacity<9.0.0,>=8.1.0
  Using cached tenacity-8.2.3-py3-none-any.whl (24 kB)
Collecting distro<2,>=1.7.0
  Using cached distro-1.9.0-py3-none-any.whl (20 kB)
Collecting httpx<1,>=0.23.0
  Using cached httpx-0.26.0-py3-none-any.whl (75 kB)
Collecting sniffio
  Using cached sniffio-1.3.0-py3-none-any.whl (10 kB)
Collecting regex>=2022.1.18
  Using cached regex-2023.12.25-cp311-cp311-win_amd64.whl (269 kB)
Collecting attrs>=17.3.0
  Using cached attrs-23.2.0-py3-none-any.whl (60 kB)
Collecting multidict<7.0,>=4.5
  Using cached multidict-6.0.4-cp311-cp311-win_amd64.whl (28 kB)
Collecting yarl<2.0,>=1.0
  Using cached yarl-1.9.4-cp311-cp311-win_amd64.whl (76 kB)
Collecting frozenlist>=1.1.1
  Using cached frozenlist-1.4.1-cp311-cp311-win_amd64.whl (50 kB)
Collecting aiosignal>=1.1.2
  Using cached aiosignal-1.3.1-py3-none-any.whl (7.6 kB)
Requirement already satisfied: pytz in c:\users\administrator\appdata\local\programs\python\python311\lib\site-packages (from clickhouse-connect>=0.5.7->chromadb==0.3.29->voyager==0.1) (2023.3.post1)
Collecting zstandard
  Using cached zstandard-0.22.0-cp311-cp311-win_amd64.whl (511 kB)
Collecting lz4
  Using cached lz4-4.3.3-cp311-cp311-win_amd64.whl (99 kB)
Collecting marshmallow<4.0.0,>=3.18.0
  Using cached marshmallow-3.20.2-py3-none-any.whl (49 kB)
Collecting typing-inspect<1,>=0.4.0
  Using cached typing_inspect-0.9.0-py3-none-any.whl (8.8 kB)
Collecting httpcore==1.*
  Using cached httpcore-1.0.2-py3-none-any.whl (76 kB)
Collecting h11<0.15,>=0.13
  Using cached h11-0.14.0-py3-none-any.whl (58 kB)
Collecting jsonpointer>=1.9
  Using cached jsonpointer-2.4-py2.py3-none-any.whl (7.8 kB)
Collecting packaging<24.0,>=23.2
  Using cached packaging-23.2-py3-none-any.whl (53 kB)
Collecting coloredlogs
  Using cached coloredlogs-15.0.1-py2.py3-none-any.whl (46 kB)
Requirement already satisfied: flatbuffers in c:\users\administrator\appdata\local\programs\python\python311\lib\site-packages (from onnxruntime>=1.14.1->chromadb==0.3.29->voyager==0.1) (23.5.26)
Collecting protobuf
  Using cached protobuf-4.25.2-cp310-abi3-win_amd64.whl (413 kB)
Collecting sympy
  Using cached sympy-1.12-py3-none-any.whl (5.7 MB)
Collecting python-dateutil>=2.8.2
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting tzdata>=2022.1
  Using cached tzdata-2023.4-py2.py3-none-any.whl (346 kB)
Collecting six>=1.5
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Requirement already satisfied: monotonic>=1.5 in c:\users\administrator\appdata\local\programs\python\python311\lib\site-packages (from posthog>=2.4.0->chromadb==0.3.29->voyager==0.1) (1.6)
Collecting backoff>=1.10.0
  Using cached backoff-2.2.1-py3-none-any.whl (15 kB)
Collecting greenlet!=0.4.17
  Using cached greenlet-3.0.3-cp311-cp311-win_amd64.whl (292 kB)
Collecting huggingface_hub<1.0,>=0.16.4
  Using cached huggingface_hub-0.20.2-py3-none-any.whl (330 kB)
Collecting click>=7.0
  Using cached click-8.1.7-py3-none-any.whl (97 kB)
Collecting httptools>=0.5.0
  Using cached httptools-0.6.1-cp311-cp311-win_amd64.whl (55 kB)
Collecting python-dotenv>=0.13
  Using cached python_dotenv-1.0.0-py3-none-any.whl (19 kB)
Collecting watchfiles>=0.13
  Using cached watchfiles-0.21.0-cp311-none-win_amd64.whl (280 kB)
Collecting websockets>=10.4
  Using cached websockets-12.0-cp311-cp311-win_amd64.whl (124 kB)
Collecting filelock
  Using cached filelock-3.13.1-py3-none-any.whl (11 kB)
Collecting fsspec>=2023.5.0
  Using cached fsspec-2023.12.2-py3-none-any.whl (168 kB)
Collecting mypy-extensions>=0.3.0
  Using cached mypy_extensions-1.0.0-py3-none-any.whl (4.7 kB)
Collecting humanfriendly>=9.1
  Using cached humanfriendly-10.0-py2.py3-none-any.whl (86 kB)
Requirement already satisfied: mpmath>=0.19 in c:\users\administrator\appdata\local\programs\python\python311\lib\site-packages (from sympy->onnxruntime>=1.14.1->chromadb==0.3.29->voyager==0.1) (1.3.0)
Requirement already satisfied: pyreadline3 in c:\users\administrator\appdata\local\programs\python\python311\lib\site-packages (from humanfriendly>=9.1->coloredlogs->onnxruntime>=1.14.1->chromadb==0.3.29->voyager==0.1) (3.4.1)
Installing collected packages: cchardet, zstandard, websockets, urllib3, tzdata, typing-extensions, tenacity, sympy, sniffio, six, regex, PyYAML, python-dotenv, psutil, protobuf, packaging, overrides, numpy, mypy-extensions, multidict, lz4, jsonpointer, javascript, idna, humanfriendly, httptools, h11, greenlet, fsspec, frozenlist, filelock, duckdb, distro, colorama, cloudpickle, charset-normalizer, chardet, certifi, backoff, attrs, yarl, typing-inspect, tqdm, SQLAlchemy, requests, python-dateutil, pydantic, pulsar-client, marshmallow, jsonpatch, httpcore, hnswlib, gymnasium, coloredlogs, clickhouse-connect, click, anyio, aiosignal, watchfiles, uvicorn, tiktoken, starlette, posthog, pandas, onnxruntime, minecraft_launcher_lib, langsmith, huggingface_hub, httpx, dataclasses-json, aiohttp, tokenizers, openai, langchain-core, fastapi, langchain-community, chromadb, langchain, voyager
  DEPRECATION: cchardet is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for cchardet ... error
  error: subprocess-exited-with-error

  × Running setup.py install for cchardet did not run successfully.
  │ exit code: 1
  ╰─> [24 lines of output]
      running install
      C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-311
      creating build\lib.win-amd64-cpython-311\cchardet
      copying src\cchardet\version.py -> build\lib.win-amd64-cpython-311\cchardet
      copying src\cchardet\__init__.py -> build\lib.win-amd64-cpython-311\cchardet
      running build_ext
      building 'cchardet._cchardet' extension
      creating build\temp.win-amd64-cpython-311
      creating build\temp.win-amd64-cpython-311\Release
      creating build\temp.win-amd64-cpython-311\Release\src
      creating build\temp.win-amd64-cpython-311\Release\src\cchardet
      creating build\temp.win-amd64-cpython-311\Release\src\ext
      creating build\temp.win-amd64-cpython-311\Release\src\ext\uchardet
      creating build\temp.win-amd64-cpython-311\Release\src\ext\uchardet\src
      creating build\temp.win-amd64-cpython-311\Release\src\ext\uchardet\src\LangModels
      "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.38.33130\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -Isrc/ext/uchardet/src -IC:\Users\Administrator\AppData\Local\Programs\Python\Python311\include -IC:\Users\Administrator\AppData\Local\Programs\Python\Python311\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.38.33130\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" /EHsc /Tpsrc/cchardet\_cchardet.cpp /Fobuild\temp.win-amd64-cpython-311\Release\src/cchardet\_cchardet.obj
      _cchardet.cpp
      src/cchardet\_cchardet.cpp(196): fatal error C1083: Cannot open include file: 'longintrepr.h': No such file or directory
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.38.33130\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> cchardet

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

[notice] A new release of pip available: 22.3 -> 23.3.2
[notice] To update, run: python.exe -m pip install --upgrade pip

C:\Users\Administrator\Desktop\asd\Voyager>

**Comment by Coppelian** [comment]
The methods for solving this problem typically include the following steps:

1. Ensure your Python environment is up to date. Run the following command in the command line to update pip:
`
pip install --upgrade pip
`

2. Make sure you have installed both setuptools and wheel Python packages. They are necessary for handling the pyproject.toml file. You can install them using the following command:
`
pip install setuptools wheel
`

3. If the problem persists, you may need to check if you have installed the correct version of Python. Some Python packages may only support specific versions of Python. You can check your Python version using the following command:
`
python --version
`

4. If your project requires a pyproject.toml file but you don't have one, you may need to check the project's build and installation process. Some projects may require manually generating the pyproject.toml file before building or installing. (Voyager should already provided toml file)

This is how I resolved this issue, I hope it helps you.

**Comment by nickgannon10** [comment]
This worked for me thanks!
