### ISSUE TITLE
the error on run "npx tsc" 

### ISSUE THREAD

**Issue by jiabin-guo** [MineDojo/Voyager#150]
npx tsc
src/BlockVeins.ts:25:32 - error TS2345: Argument of type 'import("/home/gjb/DRL/Voyager/voyager/env/mineflayer/node_modules/mineflayer/node_modules/prismarine-block/index").Block' is not assignable to parameter of type 'import("/home/gjb/DRL/Voyager/voyager/env/mineflayer/node_modules/prismarine-block/index").Block'.
  The types returned by 'getProperties()' are incompatible between these types.
    Type '{ [key: string]: string | number | boolean; }' is not assignable to type '{ [key: string]: string | number; }'.
      'string' index signatures are incompatible.
        Type 'string | number | boolean' is not assignable to type 'string | number'.
          Type 'boolean' is not assignable to type 'string | number'.

25           if (targets.includes(neighbor)) continue
                                  ~~~~~~~~

src/BlockVeins.ts:26:29 - error TS2345: Argument of type 'import("/home/gjb/DRL/Voyager/voyager/env/mineflayer/node_modules/mineflayer/node_modules/prismarine-block/index").Block' is not assignable to parameter of type 'import("/home/gjb/DRL/Voyager/voyager/env/mineflayer/node_modules/prismarine-block/index").Block'.

26           if (open.includes(neighbor)) continue
                               ~~~~~~~~

src/BlockVeins.ts:28:21 - error TS2345: Argument of type 'import("/home/gjb/DRL/Voyager/voyager/env/mineflayer/node_modules/mineflayer/node_modules/prismarine-block/index").Block' is not assignable to parameter of type 'import("/home/gjb/DRL/Voyager/voyager/env/mineflayer/node_modules/prismarine-block/index").Block'.

28           open.push(neighbor)
                       ~~~~~~~~

src/CollectBlock.ts:209:23 - error TS2345: Argument of type 'import("/home/gjb/DRL/Voyager/voyager/env/mineflayer/node_modules/prismarine-block/index").Block' is not assignable to parameter of type 'import("/home/gjb/DRL/Voyager/voyager/env/mineflayer/node_modules/mineflayer/node_modules/prismarine-block/index").Block'.
  Type 'Block' is missing the following properties from type 'Block': setSignText, getSignText

209         await bot.dig(block);
                          ~~~~~


Found 4 errors in 2 files.

Errors  Files
     3  src/BlockVeins.ts:25
     1  src/CollectBlock.ts:209
my version of Node.js is v20.11.1 and  npm is 10.5.0

**Comment by jcobol** [comment]
I have the same error, but on Windows.
Node v20.11.1.
npm 10.2.4

**Comment by jw1yuan** [comment]
Bump prismarine-block to 1.17.1
https://github.com/MineDojo/Voyager/pull/138#issue-2055259082

**Comment by romechenko** [comment]
Thanks I had same issue and @jw1yuan's comment solved it

**Comment by jiabin-guo** [comment]
i solve it
