### ISSUE TITLE
npx tsc giving error when running it

### ISSUE THREAD

**Issue by occulusgamernerd** [MineDojo/Voyager#156]
### Briefly describe your issue
...When I run the 'npx install' command, the command line is giving me multiple errors.
### Please provide your python, nodejs, Minecraft, and Fabric versions here
...Python" 3.12, Node.js: 20.12.2 Minecraft: latest

 Fabric: latest.
### [If applicable] Please provide the Minefalyer and Minecraft logs, you can find the log under `logs` folder
...
### [If applicable] Please provide the GPT conversations that are printed each round.
...
I would really appreciate it if you could help me with this!

![image_2024-04-19_195041833](https://github.com/MineDojo/Voyager/assets/167595001/46372f3d-2359-4415-94bd-f2325fc21b0f)

**Comment by xmdszzz** [comment]
hey bro, i have same problem! do you solve this?

**Comment by xmdszzz** [comment]
@occulusgamernerd hey bro, i have same problem! have this problem been solved?

**Comment by git0some** [comment]
had the same issue

this was solving it for me:
rm -fR /usr/local/lib/node_modules/npx/node_modules/npm/node_modules/graceful-fs
npm install typescript
npx tsc

... went like a charm

**Comment by cyh2004** [comment]
https://github.com/MineDojo/Voyager/pull/138#issue-2055259082 can solve this
