### ISSUE TITLE
Instructions for Replay Mod Recording

### ISSUE THREAD

**Issue by egeozguroglu** [MineDojo/Voyager#158]
Hi, could you share detailed instructions or the specific script / setup used to generate your demo videos (with replay-mod) as mentioned [here](https://github.com/MineDojo/Voyager/issues/19)? 

@xieleo5 mentioned on [Issue 19](https://github.com/MineDojo/Voyager/issues/19): "Video of our demo is generated by [replay-mod](https://www.replaymod.com/). We start the recording and let the bot play for hours, then come back to the recording and render the view from the bot." 

The above should clarify this anyway, but: did you record during training specifically, or by instantiating a learned ckpt? Thanks!

**Comment by xieleo5** [comment]
Hi, after adding the replay mod, each time you enter the game, it will automatically record all the events that happened in the game. We record both during training and during downstream task evaluation.

**Comment by egeozguroglu** [comment]
@xieleo5 Did you use replay mod on fabric server-side?
