### ISSUE TITLE
Voyager

### ISSUE THREAD

**Issue by oleg12054** [MineDojo/Voyager#159]
Please tell me if I can install and use Voyager for Fabric version 1.20.1 + Modpack of 23 mods? 

I also have a question about how to download Voyager correctly, it seems to me that it would be very good if you created a Video lesson or several video lessons 1) how to install 2) how to use 3) how to upgrade to other versions 4) how to install other dependencies and mods 5) How to use Voyager ChatGpt 3.5

**Comment by xieleo5** [comment]
Hi, I think as long as you can start a multiperson game and allow the bot to join, you can run Voyager. It's compatible with many different versions of the Fabric / MC game. 

We currently don't have enough bandwidth for a video tutorial. We welcome members of the community to create and share tutorials.

**Comment by azw2002** [comment]
There are 2 videos on youtube on how to do the installation. Is Good but incomplete.
https://www.youtube.com/@ProgramwithMinecraft
There is a ticket on here # 157 with some info on how to get working with LLama3. 
Is there a slack or discord community for voyager somewhere?
