### ISSUE TITLE
pip install failed about hnswlib in Macos

### ISSUE THREAD

**Issue by go-maple** [MineDojo/Voyager#16]
Try to use export  HNSWLIB_NO_NATIVE=1 before the pip install.

**Comment by ProjectAtlantis-dev** [comment]
That didn't work for me - the root problem is a long-running bug in chardet itself

Replace cchardet in the requirements.txt file with faust-cchardet

**Comment by apirrone** [comment]
I fixed this (on ubuntu 20.04) by installing python3.9-dev

**Comment by MatthewPDingle** [comment]
I fixed this by installing python 3.9 on windows 11 as well

**Comment by xieleo5** [comment]
The issue will be closed due to a lack of activity, feel free to reopen it if you would like to continue the discussion.

**Comment by Sohojoe** [comment]
I had the same problem on Windows11 with Python 3.11 as a Conda environment. Python 3.10 worked for me

```
ERROR: Could not build wheels for cchardet, which is required to install pyproject.toml-based projects
```
