### ISSUE TITLE
Setting up Voyager on llama3-70b and a question.

### ISSUE THREAD

**Issue by azw2002** [MineDojo/Voyager#161]
### Before submitting an issue, make sure you read the [FAQ.md](FAQ.md)
My son is attempting to setup Voyager with an OpenSource LLM. 
Followed a path similar to the one described by TimeLordRaps in issue #157.
Got stuck with code running but failing with an assertion error that he doesn;t know how to debug.

Question: Is there any open source community on slack/discord/reddit/somewhere else working on Voyager?
 
### Briefly describe your issue
He stood up the code base and got it all running with OpenAI as well as both mcport and Azure. Now he is trying to switch it from OpenAI to an OpenSource LLM.
Same kind of changes but different LLM location and model. 
LLM model llama3-70b-8192
using huggingface embeddings model name sangmini/msmarco-cotmae-MiniLM-L12_en-ko-ja
(He picked this embeddings to get around the dimensionality issue of 1536 vs 768)

The code runs and minecraft opens and begins executing. (data below)
Tasks are buffered but it encounters an assertion error.

### Please provide your python, nodejs, Minecraft, and Fabric versions here
Python version: 3.9.13
nodejs version: v18.20.2
Minecraft version: 1.19 
Fabric version: 0.14.18-1.19

### [If applicable] Please provide the GPT conversations that are printed each round.
python3 3.py
C:\Users\clewr\.pyenv\pyenv-win\versions\3.9.13\lib\site-packages\langchain\chat_models\__init__.py:31: LangChainDeprecationWarning: Importing chat models from langchain is deprecated. Importing from langchain will no longer be supported as of langchain==0.2.0. Please import from langchain-community instead:

`from langchain_community.chat_models import ChatOpenAI`.

To install langchain-community run `pip install -U langchain-community`.
  warnings.warn(
C:\Users\clewr\.pyenv\pyenv-win\versions\3.9.13\lib\site-packages\langchain\chat_models\__init__.py:31: LangChainDeprecationWarning: Importing chat models from langchain is deprecated. Importing from langchain will no longer be supported as of langchain==0.2.0. Please import from langchain-community instead:

`from langchain_community.chat_models import ChatOpenAI`.

To install langchain-community run `pip install -U langchain-community`.
  warnings.warn(
Creating Minecraft server
Loading Action Agent from C:\Users\clewr\VoyagerTrial\Voyager\ckpt/action
Loading Curriculum Agent from C:\Users\clewr\VoyagerTrial\Voyager\ckpt/curriculum
C:\Users\clewr\.pyenv\pyenv-win\versions\3.9.13\lib\site-packages\huggingface_hub\file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
Loading Skill Manager from C:\Users\clewr\VoyagerTrial\Voyager\ckpt/skill
C:\Users\clewr\.pyenv\pyenv-win\versions\3.9.13\lib\site-packages\huggingface_hub\file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
Starting Minecraft server
Subprocess minecraft started with PID 7672.
The mc server is listening on port 54922
Server started on port 54922
Mineflayer process has exited, restarting
Subprocess mineflayer started with PID 24264.
Server started on port 3000

C:\Users\clewr\.pyenv\pyenv-win\versions\3.9.13\lib\site-packages\langchain_core\_api\deprecation.py:119: LangChainDeprecationWarning: The method `BaseChatModel.__call__` was deprecated in langchain-core 0.1.7 and will be removed in 0.3.0. Use invoke instead.
  warn_deprecated(
Curriculum Agent Question: How to defeat a pig for food?
Curriculum Agent Answer: To defeat a pig for food in Minecraft, you'll need to attack and kill it. You can do this by hitting the pig with your bare hands or with a weapon, such as a sword or an axe. Once the pig is killed, it will drop porkchops, which can be picked up and added to your inventory as a food source.
C:\Users\clewr\.pyenv\pyenv-win\versions\3.9.13\lib\site-packages\langchain_core\_api\deprecation.py:119: LangChainDeprecationWarning: Since Chroma 0.4.x the manual persistence method is no longer supported as docs are automatically persisted.
  warn_deprecated(
Curriculum Agent Question: What are the benefits of using a stone pickaxe over a wooden pickaxe?
Curriculum Agent Answer: The benefits of using a stone pickaxe over a wooden pickaxe are that it is more durable and can mine resources more efficiently. A stone pickaxe has a longer lifespan and can mine stone and coal ore, whereas a wooden pickaxe can only mine dirt, gravel, and wood. Additionally, a stone pickaxe mines resources faster than a wooden pickaxe.
Traceback (most recent call last):
  File "C:\Users\clewr\VoyagerTrial\Voyager\3.py", line 22, in <module>
    voyager.learn()
  File "C:\Users\clewr\VoyagerTrial\Voyager\voyager\voyager.py", line 321, in learn
    task, context = self.curriculum_agent.propose_next_task(
  File "C:\Users\clewr\VoyagerTrial\Voyager\voyager\agents\curriculum.py", line 278, in propose_next_task
    self.render_human_message(
  File "C:\Users\clewr\VoyagerTrial\Voyager\voyager\agents\curriculum.py", line 213, in render_human_message
    questions, answers = self.run_qa(
  File "C:\Users\clewr\VoyagerTrial\Voyager\voyager\agents\curriculum.py", line 403, in run_qa
    assert question not in self.qa_cache
AssertionError
Exception ignored in: <module 'threading' from 'C:\\Users\\clewr\\.pyenv\\pyenv-win\\versions\\3.9.13\\lib\\threading.py'>
Traceback (most recent call last):
  File "C:\Users\clewr\.pyenv\pyenv-win\versions\3.9.13\lib\threading.py", line 1477, in _shutdown
    lock.acquire()
KeyboardInterrupt:
Stopping mineflayer
Terminate batch job (Y/N)? y

**Comment by azw2002** [comment]
Added .invoke to all llm calls in each .py file in the agents directory and also deleted the ckpt directory to start with a blank installation setup. Now running. Would still like to know if there is a community working on this somewhere?

**Comment by Bluedrake42** [comment]
Hi, I just picked this up and would be interested in helping.

**Comment by ahfmrptEkd** [comment]
Thank you for info.
