### ISSUE TITLE
MC seeds used by Voyager's skill libraries

### ISSUE THREAD

**Issue by egeozguroglu** [MineDojo/Voyager#162]
Hi! Could you provide the seeds used for the three released trials? It should be available as level-seed in server.properties. Thanks!

**Comment by xieleo5** [comment]
Hi, I'm sorry, but the checkpoints are on my old PC, and I've not been able to access them recently. I can follow up with the seed after ~ three months.

**Comment by egeozguroglu** [comment]
Thanks, please let us know when you have them. We're looking to benchmark Voyager as a baseline.

**Comment by egeozguroglu** [comment]
Any updates here?
