### ISSUE TITLE
 Is Voyager built on top of MineDojo?

### ISSUE THREAD

**Issue by MurakamiNatsuki** [MineDojo/Voyager#167]
Hello,

There was no response to this issue(https://github.com/MineDojo/Voyager/issues/133), so I'd like to ask again. The paper mentions that Voyager is built on top of MineDojo, but I can't understand the relationship between MineDojo and Voyager from the code. Could someone please explain this?

Thank you very much.

**Comment by ahfmrptEkd** [comment]
I would read a code in MineDojo repo and compare them.
But voyager paper came out after Minedojo paper came out about 1 year.
