### ISSUE TITLE
bot falls out and dies after entering server

### ISSUE THREAD

**Issue by spearsheep** [MineDojo/Voyager#169]
### Briefly describe your issue
so I followed the setup and downloaded all the mod packs, manually compiled the better respawn mod at branch 1.19. However, after I enter the server with voyager.decompose_task(task=task), I would immediately encouter the following error continously:
 Mineflayer process has exited, restarting
Subprocess mineflayer started with PID 36748.

So I followed one of the posts and commented out the following lines in index.js:
const collectBlock = require("mineflayer-collectblock").plugin;
const minecraftHawkEye = require("minecrafthawkeye");
I also uncommented the following lines:
// bot.collectBlock.movements.digCost = 0;
// bot.collectBlock.movements.placeCost = 0;

After this, I start to encounter the new error that directly after the bot enters it fells out of the world and dies. But the task decomposition and inference continues until the error: list out of index to some sort of events.

### Please provide your python, nodejs, Minecraft, and Fabric versions here
Python 3.10.14, Minecraft 1.19, nodejs v20.14.0,

better-respawn-fabric-1.19-2.0.0.jar
completeconfig-2.0.0.jar
fabric-api-0.58.0+1.19.jar
modmenu-4.0.4.jar
Multiplayer-Server-Pause-1.19-Fabric-1.1.0.ja

**Comment by pj0620** [comment]
Any progress on this on this? I am seeing the same issue.

**Comment by zhang-song-bo** [comment]
I also encountered the same situation as yours. May I ask if you have solved the problem now?
