### ISSUE TITLE
No module named voyager.utils

### ISSUE THREAD

**Issue by Rypex** [MineDojo/Voyager#171]
### Briefly describe your issue
I have successfully completed the setup without errors. After I fixed the Prismarine bug. I created the Python file with mc_port and specified the API key. Now I get the following error:

C:\Users\rypex\Desktop\Voyager-main\voyager>Python3 1.py
Traceback (most recent call last):
  File "C:\Users\rypex\Desktop\Voyager-main\voyager\1.py", line 1, in <module>
    from voyager import Voyager
  File "C:\Users\rypex\Desktop\Voyager-main\voyager\voyager.py", line 7, in <module>
    import voyager.utils as U
ModuleNotFoundError: No module named 'voyager.utils'; 'voyager' is not a package

### Please provide your python, nodejs, Minecraft, and Fabric versions here
Python 3.9.13 NodeJS 22.9.0

**Comment by Rypex** [comment]
that is the simple code is used:

> from voyager import Voyager
> 
> openai_api_key = "KEY is entered"
> 
> voyager = Voyager(
>     mc_port=*Port is entered*,
>     openai_api_key=openai_api_key,
> )
> 
> voyager.learn()

**Comment by Ranpu123** [comment]
@Rypex try creating the file in the main Voyager folder.
