### ISSUE TITLE
远程主机强制关闭了一个现有的连接

### ISSUE THREAD

**Issue by BlackTea-c** [MineDojo/Voyager#174]
### Briefly describe your issue
Bot join the game and kill itself and quit the game.
### Please provide your python, nodejs, Minecraft, and Fabric versions here
D:\Voyager\Voyager\venv\lib\site-packages\langchain\chat_models\__init__.py:33: LangChainDeprecationWarning: Importing chat models from langchain is deprecated. Importing from langchain will no longer be supported as of langchain==0.2.0. Please import from langchain-community instead:

`from langchain_community.chat_models import ChatOpenAI`.

To install langchain-community run `pip install -U langchain-community`.
  warnings.warn(
D:\Voyager\Voyager\venv\lib\site-packages\langchain\chat_models\__init__.py:33: LangChainDeprecationWarning: Importing chat models from langchain is deprecated. Importing from langchain will no longer be supported as of langchain==0.2.0. Please import from langchain-community instead:

`from langchain_community.chat_models import ChatOpenAI`.

To install langchain-community run `pip install -U langchain-community`.
  warnings.warn(
D:\Voyager\Voyager\voyager\agents\curriculum.py:10: LangChainDeprecationWarning: Importing OpenAIEmbeddings from langchain.embeddings is deprecated. Please replace deprecated imports:

>> from langchain.embeddings import OpenAIEmbeddings

with new imports of:

>> from langchain_community.embeddings import OpenAIEmbeddings
You can use the langchain cli to **automatically** upgrade many imports. Please see documentation here <https://python.langchain.com/v0.2/docs/versions/v0_2/>
  from langchain.embeddings.openai import OpenAIEmbeddings
D:\Voyager\Voyager\voyager\agents\curriculum.py:12: LangChainDeprecationWarning: Importing Chroma from langchain.vectorstores is deprecated. Please replace deprecated imports:      

>> from langchain.vectorstores import Chroma

with new imports of:

>> from langchain_community.vectorstores import Chroma
You can use the langchain cli to **automatically** upgrade many imports. Please see documentation here <https://python.langchain.com/v0.2/docs/versions/v0_2/>
  from langchain.vectorstores import Chroma
D:\Voyager\Voyager\voyager\agents\skill.py:5: LangChainDeprecationWarning: Importing OpenAIEmbeddings from langchain.embeddings is deprecated. Please replace deprecated imports:    

>> from langchain.embeddings import OpenAIEmbeddings

with new imports of:

>> from langchain_community.embeddings import OpenAIEmbeddings
You can use the langchain cli to **automatically** upgrade many imports. Please see documentation here <https://python.langchain.com/v0.2/docs/versions/v0_2/>
  from langchain.embeddings.openai import OpenAIEmbeddings
D:\Voyager\Voyager\voyager\agents\skill.py:7: LangChainDeprecationWarning: Importing Chroma from langchain.vectorstores is deprecated. Please replace deprecated imports:

>> from langchain.vectorstores import Chroma

with new imports of:

>> from langchain_community.vectorstores import Chroma
You can use the langchain cli to **automatically** upgrade many imports. Please see documentation here <https://python.langchain.com/v0.2/docs/versions/v0_2/>
  from langchain.vectorstores import Chroma
D:\Voyager\Voyager\voyager\agents\action.py:34: LangChainDeprecationWarning: The class `ChatOpenAI` was deprecated in LangChain 0.0.10 and will be removed in 1.0. An updated version
 of the class exists in the langchain-openai package and should be used instead. To use it run `pip install -U langchain-openai` and import as `from langchain_openai import ChatOpenAI`.
  self.llm = ChatOpenAI(
D:\Voyager\Voyager\voyager\agents\curriculum.py:60: LangChainDeprecationWarning: The class `OpenAIEmbeddings` was deprecated in LangChain 0.0.9 and will be removed in 1.0. An update
d version of the class exists in the langchain-openai package and should be used instead. To use it run `pip install -U langchain-openai` and import as `from langchain_openai import OpenAIEmbeddings`.
  embedding_function=OpenAIEmbeddings(),
D:\Voyager\Voyager\voyager\agents\curriculum.py:58: LangChainDeprecationWarning: The class `Chroma` was deprecated in LangChain 0.2.9 and will be removed in 1.0. An updated version of the class exists in the langchain-chroma package and should be used instead. To use it run `pip install -U langchain-chroma` and import as `from langchain_chroma import Chroma`. 
  self.qa_cache_questions_vectordb = Chroma(
Mineflayer process has exited, restarting
Subprocess mineflayer started with PID 11520.
Server started on port 3000

Traceback (most recent call last):
  File "D:\Voyager\Voyager\venv\lib\site-packages\urllib3\connectionpool.py", line 789, in urlopen
    response = self._make_request(
  File "D:\Voyager\Voyager\venv\lib\site-packages\urllib3\connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
  File "D:\Voyager\Voyager\venv\lib\site-packages\urllib3\connection.py", line 507, in getresponse
    httplib_response = super().getresponse()
  File "D:\python396\lib\http\client.py", line 1349, in getresponse
    response.begin()
  File "D:\python396\lib\http\client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "D:\python396\lib\http\client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "D:\python396\lib\socket.py", line 704, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Voyager\Voyager\venv\lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
  File "D:\Voyager\Voyager\venv\lib\site-packages\urllib3\connectionpool.py", line 843, in urlopen
    retries = retries.increment(
  File "D:\Voyager\Voyager\venv\lib\site-packages\urllib3\util\retry.py", line 474, in increment
    raise reraise(type(error), error, _stacktrace)
  File "D:\Voyager\Voyager\venv\lib\site-packages\urllib3\util\util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "D:\Voyager\Voyager\venv\lib\site-packages\urllib3\connectionpool.py", line 789, in urlopen
    response = self._make_request(
  File "D:\Voyager\Voyager\venv\lib\site-packages\urllib3\connectionpool.py", line 536, in _make_request
    voyager.learn()
  File "D:\Voyager\Voyager\voyager\voyager.py", line 306, in learn
    self.env.reset(
  File "D:\Voyager\Voyager\voyager\env\bridge.py", line 156, in reset
    returned_data = self.check_process()
  File "D:\Voyager\Voyager\voyager\env\bridge.py", line 93, in check_process
    res = requests.post(
  File "D:\Voyager\Voyager\venv\lib\site-packages\requests\api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "D:\Voyager\Voyager\venv\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\Voyager\Voyager\venv\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\Voyager\Voyager\venv\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "D:\Voyager\Voyager\venv\lib\site-packages\requests\adapters.py", line 682, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))

**Comment by ZHUWEI-hub** [comment]
Hi,I have also encountered the same problem. How was it solved?,thank you!!!

**Comment by BlackTea-c** [comment]
Hi,just change the index.js in voyager\env\mineflayer,you can refer 
[index.txt](https://github.com/user-attachments/files/17613063/index.txt)
just copy this to the target directory and change it to index.js
