### ISSUE TITLE
openai request rate

### ISSUE THREAD

**Issue by jwjohns** [MineDojo/Voyager#20]
I let it run about an hour and it got itself rate limited with openai as well as cost ~$20 in that hour in api calls. 

It made 214 api requests in that hour to gpt-4-0314. It didn't complete any tasks. Tons of failed mine wood attempts in the log. 

is this expected behavior?

ubuntu 22.04, MC 1.19, fabric 14.18

**Comment by xieleo5** [comment]
Hi, thanks for your interest in this project. After you start running `voyager.learn()`, it's recommended to monitor the bot's actions for a period and ensure that it successfully completes some tasks. Could you also provide a sample conversation from each round? This will help us identify any issues right from the start. Each agent should print its own message, beginning with `****** XXX Agent XXXX Message *******` Please share a complete round of conversation here.

**Comment by jwjohns** [comment]
Thank you so much for the reply! I monitored it for a while, I also tested a bit myself any any mined items are not stored to even my player inventory. Its a fresh install of everything. I remember those messages in the CLI but I did not save them. I cannot find a log of that information, I was just using std.out in cli when I ran it. I will run it again and see if it occurs a second time.  

The cost and such is not any issue, and I thank you for making this code available to us. I just wanted to be sure that was expected behavior from the code regarding openai api.

**Comment by xieleo5** [comment]
The first task `Mine a wood log` is a seed task. If the bot can not even finish that task, there must be something wrong. Also, all the actions should be done by the bot, which means your player will not move or get any items. You can try to use the `/tp bot` command to see what's the bot doing.

**Comment by ShimantaBhuyan** [comment]
Hey @xieleo5 , I have seen the same behaviour. 
I was monitoring the bot for some time and saw that it mines a log for a moment, then stops for some time, and then the bot disconnects. It has been able to mine atmost 2 logs at one time before disconnecting.
Here is my run log, I ran on local minecraft port: https://pastebin.com/v2mMienh
