### ISSUE TITLE
Want to know which version that I need to buy about MC in Macos

### ISSUE THREAD

**Issue by go-maple** [MineDojo/Voyager#22]
I saw the  MC website,There are two version for paying,I don't which version that I can use it for test the Voyager.
<img width="698" alt="image" src="https://github.com/MineDojo/Voyager/assets/97354215/7d588578-f832-4c96-ad46-5676a691327b">
help!!!

**Comment by Ellen7ions** [comment]
Base Game is enough

**Comment by ProjectAtlantis-dev** [comment]
Minecraft Java - needs to be compatible w Mineflayer for sure

**Comment by go-maple** [comment]
I got it, Thanks, bro. I will buy base Game @Ellen7ions @ProjectAtlantis-dev

**Comment by go-maple** [comment]
I bought it and running 
<img width="851" alt="image" src="https://github.com/MineDojo/Voyager/assets/97354215/686b964f-0c06-4961-b34c-e37055119214">

**Comment by Wheest** [comment]
Bedrock integration for mineflayer appears to be ongoing.  There is progress and significant number of features merged.

See this issue for what else is needed for support:

https://github.com/PrismarineJS/bedrock-protocol/issues/116
