### ISSUE TITLE
Not able to find 'YOUR_MINECRAFT_GAME_LOCATION/config/better-respawn' to edit

### ISSUE THREAD

**Issue by ShimantaBhuyan** [MineDojo/Voyager#26]
In the fabric mods installation step 4:
```
After you launch the game, go to YOUR_MINECRAFT_GAME_LOCATION/config/better-respawn, and modify the properties file with ...
```
I am unable to find the file. Do I need to run the script and then edit it, or launch the game once before and then this file is generated?
I cannot see any `config` folder currently in my `.minecraft` folder location.

**Comment by taoisu** [comment]
My experience was the config only shows up after I launched the mod-ed game for the first time.

**Comment by ShimantaBhuyan** [comment]
I am unable to launch with azure login due to key error.
However I was able to start with a local LAN game, but I can't see the folder after that as well.

**Comment by GoingMyWay** [comment]
Please the better-respawn .jar file into the `mods` directory and launch the fabric mod game. Then you will see the config directory.

**Comment by ImJohnDoe** [comment]
When you run `java -jar fabric-installer-0.11.2.jar`, look at the install location that it. Here is my example on MacOS.
<img width="653" alt="install-location" src="https://github.com/MineDojo/Voyager/assets/5204392/158ca1b4-a34f-4adb-bc94-bfc1754c4b02">
