### ISSUE TITLE
Can my checkpoint be published as an example?

### ISSUE THREAD

**Issue by daswer123** [MineDojo/Voyager#27]
Hi, I think for many people spending $50 will seem like a pretty big deal. I have already spent and would like to share my [checkpoint](https://github.com/daswer123/Voyager_checkpoint) at 160it. 

Is there any way to give my checkpoint as an example so people can play without spending a lot of money?
I can't spend much time working on the project myself, but it will be interesting what people can do.

**Comment by go-maple** [comment]
Thanks for sharing.bro

**Comment by go-maple** [comment]
I have to use vpn for openai api. I don't how to use proxy for Voyager.

**Comment by wangguanzhi** [comment]
Thank you so much for your efforts @daswer123! We will release our checkpoints and include yours as an additional example soon!

**Comment by daswer123** [comment]
Cool, It will be interesting to look

**Comment by xieleo5** [comment]
Hi, @daswer123. Thank you very much for sharing your checkpoints. We included your checkpoints in [Community Contributions](https://github.com/MineDojo/Voyager/tree/main/skill_library#community-contributions).

**Comment by daswer123** [comment]
Nice, thanks :)
