### ISSUE TITLE
ERR_CONNECTION_REFUSED.

### ISSUE THREAD

**Issue by Cubey42** [MineDojo/Voyager#28]
I get this 
Creating Minecraft server
Please open https://login.microsoftonline.com/consumers/oauth2/v2.0/authorize?client_id=(removed)&response_type=code&redirect_uri=https%3A%2F%2F127.0.0.1%2Fauth-response&response_mode=query&scope=XboxLive.signin+offline_access&state=tRhwbidsvxBh7YfKKpBlBg&code_challenge=S0y5aMT54UHd34jK3HTFoPeEyJs8xxLvVJua-OoldnI&code_challenge_method=S256 in your browser and copy the url you are redirected into the prompt below.
(removed is the client_id I created)
but I just get a connection refusal each time, not sure what I've done wrong

**Comment by taoisu** [comment]
Do you have any error message?

Depending on the error message, It could be you didn't add the redirect url to the white list in the app.

**Comment by xieleo5** [comment]
Hi, thanks for your interest in this project! For connection refused, you can check [this section](https://github.com/MineDojo/Voyager/blob/main/FAQ.md#i-get-a-connection-error-after-i-click-on-the-azure-login-link-and-login-to-my-microsoft-account) in FAQ.md

**Comment by Cubey42** [comment]
Okay so I see the code it mentions per the faq, what do I do with it?

**Comment by xieleo5** [comment]
You just need to copy that link in your browser and paste it to your terminal, then hit the `Enter` key.

**Comment by Cubey42** [comment]
its still the same result. I used one like the one involved and I got this in the address box after the connection is refused https://127.0.0.1/auth-response?code=M.C107_SN1.2.90b3454c-5679-c35b-2da3-53efbc37de87&state=NLWLahsjPtvQMxrhdEGRXQ

putting this in again still gives me connection refused

**Comment by Cubey42** [comment]
oh, I'm stupid and unable to follow instructions

**Comment by xieleo5** [comment]
Hi, to protect your personal information, I edit your response. The link you just paste is the correct one. You just need to paste that one to your terminal but not your browser.

**Comment by Cubey42** [comment]
Traceback (most recent call last):
  File "H:\AI MC\Voyager\run.py", line 13, in <module>
    voyager = Voyager(
  File "H:\AI MC\Voyager\voyager\voyager.py", line 102, in __init__
    self.env = VoyagerEnv(
  File "H:\AI MC\Voyager\voyager\env\bridge.py", line 42, in __init__
    self.mc_instance = self.get_mc_instance()
  File "H:\AI MC\Voyager\voyager\env\bridge.py", line 67, in get_mc_instance
    return MinecraftInstance(
  File "H:\AI MC\Voyager\voyager\env\minecraft_launcher.py", line 36, in __init__
    self.mc_command = self.get_mc_command()
  File "H:\AI MC\Voyager\voyager\env\minecraft_launcher.py", line 89, in get_mc_command
    login_data = minecraft_launcher_lib.microsoft_account.complete_login(
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\minecraft_launcher_lib\microsoft_account.py", line 261, in complete_login
    token = token_request["access_token"]
KeyError: 'access_token'

**Comment by DamascusGit** [comment]
> Traceback (most recent call last): File "H:\AI MC\Voyager\run.py", line 13, in voyager = Voyager( File "H:\AI MC\Voyager\voyager\voyager.py", line 102, in **init** self.env = VoyagerEnv( File "H:\AI MC\Voyager\voyager\env\bridge.py", line 42, in **init** self.mc_instance = self.get_mc_instance() File "H:\AI MC\Voyager\voyager\env\bridge.py", line 67, in get_mc_instance return MinecraftInstance( File "H:\AI MC\Voyager\voyager\env\minecraft_launcher.py", line 36, in **init** self.mc_command = self.get_mc_command() File "H:\AI MC\Voyager\voyager\env\minecraft_launcher.py", line 89, in get_mc_command login_data = minecraft_launcher_lib.microsoft_account.complete_login( File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\minecraft_launcher_lib\microsoft_account.py", line 261, in complete_login token = token_request["access_token"] KeyError: 'access_token'

I'm also getting thi serror.

**Comment by xieleo5** [comment]
Hi, all. Make sure you log in to the correct Microsoft Account and set everything correctly in App Registration. You can see #18 for further information.

**Comment by yhyu13** [comment]
May be a proxy issue?

**Comment by ahaslam** [comment]
Works for me if you set the **secret_value** to **""** in the azure_login options:

`azure_login = {
    "client_id": "...",
    "redirect_url": "https://127.0.0.1/auth-response",
    "secret_value": "",
    "version": "fabric-loader-0.14.21-1.19.4", # the version Voyager is tested on
}`
