### ISSUE TITLE
How to use azure to login Minecraft?

### ISSUE THREAD

**Issue by go-maple** [MineDojo/Voyager#34]
I try to use azure login, but It doesn't callback Minecraft for running

<img width="1210" alt="image" src="https://github.com/MineDojo/Voyager/assets/97354215/df8de65b-23c7-42a3-9e30-7722a768d3b4">

<img width="1103" alt="image" src="https://github.com/MineDojo/Voyager/assets/97354215/35b7ebfe-abfc-41c8-9bf1-4f0df6c62003">

**Comment by dxdx123** [comment]
copy the redirect url to commandline，just like this。
![image](https://github.com/MineDojo/Voyager/assets/14290268/c463983a-1e13-4084-b807-44817d528082)

**Comment by go-maple** [comment]
Sorry bro,I got it,step 1:Copy the url which direct new url. step2: Copying back to the next line.

**Comment by droc12** [comment]
<img width="753" alt="image" src="https://github.com/MineDojo/Voyager/assets/126769237/41688875-ed2c-4350-9d29-8ff0f2be3360">

**Comment by go-maple** [comment]
I solved it,I created the app in azure and chose web for callback. it can work now.

**Comment by go-maple** [comment]
I solved it,I recreated the app in azure and chose web for callback. it can work now.

**Comment by GoingMyWay** [comment]
> I solved it,I recreated the app in azure and chose web for callback. it can work now.

I tried to select 'web' for callback. Same error.

**Comment by xiaoxu347** [comment]
Oh, I tried both types, KeyError: 'access_token'

**Comment by GoingMyWay** [comment]
> Oh, I tried both types, KeyError: 'access_token'

Same
