### ISSUE TITLE
resume=True?

### ISSUE THREAD

**Issue by DamascusGit** [MineDojo/Voyager#36]
since i get this error when re-running:
```
AssertionError: Skill Manager's vectordb is not synced with skills.json.
There are 3 skills in vectordb but 0 skills in skills.json.
Did you set resume=False when initializing the manager?
You may need to manually delete the vectordb directory for running from scratch.
```

do i just set resume=True when i call 

```python3 voyagerscript.py resume=True```

or do I place the resume arg somewhere else?

**Comment by TimeLordRaps** [comment]
you want resume=True in the Voyager() example:
`my_voyager = Voyager(
    azure_login=azure_login,
    openai_api_key=openai_api_key,
    resume=True,
    )`
You may also need to specify the checkpoint directory if you specified it to something other than the default when running the first time, also it will start count from where the iterations were last so if it hit max iterations, you would need to increase it.

**Comment by xieleo5** [comment]
Hi, we just updated [README](https://github.com/MineDojo/Voyager#resume-from-a-checkpoint-during-learning) for the resume.
