### ISSUE TITLE
Inquiry Regarding Resource Utilization and Associated Costs for GPT-4 and GPT-3.5

### ISSUE THREAD

**Issue by Shenzhi-Wang** [MineDojo/Voyager#4]
Dear Team,

First and foremost, I'd like to express my deep appreciation for the excellent work you have accomplished in this project. The level of professionalism and detail in your work is truly commendable.

As I'm looking forward to running your code, I am trying to estimate the associated costs. I was wondering **if you could provide a rough estimation for the computational cost of running, for instance, 150 prompting iterations on both the GPT-4 and GPT-3.5 models**?

This information would be highly beneficial in planning for my resource allocation. I understand the cost might vary based on several factors, however, any approximation or range would be greatly appreciated.

Thank you for your attention and assistance with this matter.

Best Regards.

**Comment by daswer123** [comment]
For me, the cost of 160 iterations, was ~**$40**
The training took about 6 hours on default settings.

In my [repo](https://github.com/daswer123/Voyager_chekpoit) I posted a checkpoint of 160 iterations

**Comment by Shenzhi-Wang** [comment]
> For me, the cost of 160 iterations, was ~**$40** The training took about 6 hours on default settings.
> 
> In my [repo](https://github.com/daswer123/Voyager_checkpoint) I posted a checkpoint of 160 iterations

Thanks for your response!
