### ISSUE TITLE
General issues with Cheats not enabled

### ISSUE THREAD

**Issue by TimeLordRaps** [MineDojo/Voyager#41]
Main issue: 
Bot leaves after task and does not rejoin. 

Secondary issues with the presence of cheats: 
Bot toggles tile drops, this seems unnecessary and, in my opinion, should not be toggled. 
Also freezing the entire server is not really a useful strategy for cooperating with bots. Instead in my opinion the bot should leave and join the server when it would freeze and unfreeze it. This could be considered as a player's time to think in between overarching tasks, really only draws similarities to larger time-scale tasks in humans.
For the keep inventory toggling, I think this should really be an optional parameter rather than an assumed necessity, in my opinion the bot should be able to be tested if it can handle death.

**Comment by theblazehen** [comment]
Regarding pause: You can at least edit voyager/env/bridge.py to remove that functionality
