### ISSUE TITLE
`KeyError: 'Token'` when creating Minecraft server

### ISSUE THREAD

**Issue by Benjamin-eecs** [MineDojo/Voyager#43]
Hi there, I followed the instructions in README to copy the url from browser, the url is "https://127.0.0.1/auth-response?code=M.CXXXXXXXXXX&state=XXXXXXXXXX", and it led me to the following

![image](https://github.com/MineDojo/Voyager/assets/32269413/a6a5e0c7-dbc9-4a87-8568-32bf928cd0e3)

Already followed the intruction to change the app to `web`, still not working :(

**Comment by xieleo5** [comment]
Hi, thanks for your interest. If none of the methods work for you, please check the original tutorial in [minecraft-launcher-lib](https://minecraft-launcher-lib.readthedocs.io/en/stable/tutorial/microsoft_login.html) 

I'm sorry about that, but I cannot reproduce the error on my machine so I cannot provide further suggestions.

**Comment by abcdvzz** [comment]
I got the same error, have you solved it?
