### ISSUE TITLE
ERR_CONNECTION_REFUSED when I use browser to access the created minecraft server

### ISSUE THREAD

**Issue by qyxqyx** [MineDojo/Voyager#46]
I follow the tutorial in the installation blog to create the minecraft server on my local computer, and the program returns the first link (https://login.microsoftonline.com/consumers/oauth2/v2.0/authorize?client_id=********) to me so that I can access the server in browser. 

By clicking the link, I jump to a website where I was required to loggin with my microsoft account. 

After loggin, the website address turns to the second link (https://127.0.0.1/auth-response?code=*******) and raises an error: ERR_CONNECTION_REFUSED. 

How can I solve this error? Asking for help

**Comment by Cubey42** [comment]
use that hyperlink and paste it back into the terminal, then hit enter

**Comment by qyxqyx** [comment]
Thanks. This issue is address with your help

**Comment by xieleo5** [comment]
Close since the issue is resolved.
