### ISSUE TITLE
How to use proxy for testing this code?

### ISSUE THREAD

**Issue by go-maple** [MineDojo/Voyager#49]
I have to use the vpn for testing this code. When I open vpn for test.

I try to use this code:
"""
voyager = Voyager(
    azure_login=azure_login,
    skill_manager_retrieval_top_k=0,
    max_iterations=200,
    resume=True,
    ckpt_dir="./checkpoints/ckpt",
    openai_api_key=openai_api_key,
)

voyager.learn()
"""

<img width="1078" alt="image" src="https://github.com/MineDojo/Voyager/assets/97354215/38ceaf3b-6714-4623-8988-aa0fdaa8e29e">

<img width="1081" alt="image" src="https://github.com/MineDojo/Voyager/assets/97354215/77f6297e-a54a-499d-bfe7-462d00a692b0">

<img width="964" alt="image" src="https://github.com/MineDojo/Voyager/assets/97354215/d1b0cd74-f488-457b-8e9d-fbfe7d74aff2">

always have many errors.
I need help!!!

**Comment by xieleo5** [comment]
Hi, I think the proxy is not a problem. Can you share your Mineflayer log here? It's under `logs/mineflayer`.

**Comment by go-maple** [comment]
@xieleo5 please analyze  this log. tks
[20230531_143639.log.zip](https://github.com/MineDojo/Voyager/files/11609671/20230531_143639.log.zip)

**Comment by xieleo5** [comment]
Hi, I found that you have `2023-05-31 14:38:17,620 - mineflayer - INFO - Prismarine viewer web server running on *:3001` this line in your log. Did you try to add Prismarine viewer yourself?

**Comment by go-maple** [comment]
I don't why always throw this error.
