### ISSUE TITLE
Error in the line: access_token = account_request["access_token"].  Error is: KeyError: 'access_token'

### ISSUE THREAD

**Issue by qyxqyx** [MineDojo/Voyager#57]
I follow the installation tutorial to deploy Voyager on my computer, but meet an error in the line: access_token = account_request["access_token"]. 

The error is: KeyError: 'access_token'. 

I print the dict account_request, and the contents are:  {'path': '/authentication/login_with_xbox', 'error':'FORBIDDEN'}, which does not contain the key 'access_token'.

Can someone help my to solve this issue? Thanks.

**Comment by xieleo5** [comment]
Hi, if you really cannot do Azure login, please use mc_port. You will just need to manually resume if the process crashes.

**Comment by steppelord** [comment]
I get the same error @ItsBean 

is your account a third party Microsoft account? (E.g. gmail) 

I wonder if that could be the reason?
