### ISSUE TITLE
What version are you using?

### ISSUE THREAD

**Issue by sirousagisan** [MineDojo/Voyager#58]
I am new to both Minecraft and mods.
I'm trying to create a minecraft world but I'm getting errors.
I think the error is due to the mod version.
I am using version 1.19.4 of minecraft and mods,
but the version of "Multiplayer Server Pause" does not match.
I would therefore like to know the version you are running.

**Comment by GoingMyWay** [comment]
Please use 1.19. Do not use 1.19.4 which is not compatible.


Follow this comment https://github.com/MineDojo/Voyager/issues/10#issuecomment-1565482721 to build better-respawn.
