### ISSUE TITLE
access_token = account_request["access_token"] KeyError: 'access_token'

### ISSUE THREAD

**Issue by ItsBean** [MineDojo/Voyager#59]
Upon trying to authenticate with the Minecraft API via Xbox, I'm encountering a 'FORBIDDEN' error. Here's the returned value:

`account_request:  {'path': '/authentication/login_with_xbox', 'error': 'FORBIDDEN'}`

Could anyone provide some insight into why this may be occurring, and offer potential solutions to resolve this issue?

**Comment by xieleo5** [comment]
Do you buy the Minecraft game in that account?

**Comment by xieleo5** [comment]
Seems to be same issue as #54, let's just leave the discussion there.

**Comment by xieleo5** [comment]
Can you try to run `node index.js` under `voyager/env/mineflayer` directory? After doing so, could you also check is there anything listening at that port 3000?

**Comment by xieleo5** [comment]
Seems that the node js starts normally. Before you continue, make sure you kill all the processes you just started. Then, start your Minecraft game through the official launcher. Open the world to LAN and record the port number. Finally, you can run Voyager with mc_port you just recorded.

**Comment by BrunoFANG1** [comment]
I met the same problem, please tell me how you solved it.

**Comment by ASAITuber** [comment]
> Seems that the node js starts normally. Before you continue, make sure you kill all the processes you just started. Then, start your Minecraft game through the official launcher. Open the world to LAN and record the port number. Finally, you can run Voyager with mc_port you just recorded.

What page should I check to see how to start Voyager using mc-port?

**Comment by GoingMyWay** [comment]
Same issue with Azure. Even using 'web' for the callback, it still cannot address the problem.
