### ISSUE TITLE
https://127.0.0.1/auth-response connection refused

### ISSUE THREAD

**Issue by world-DESIGNER** [MineDojo/Voyager#6]
I ran the python script in README.md
and this showed up

Please open https://login.microsoftonline.com/consumers/oauth2/v2.0/authorize?client_id=... in your browser and copy the url you are redirected into the prompt below.

but whenever I click this link after I logged in microsoft account, I constantly get connection refused from 127.0.0.1

I'm not sure if this is a particular problem of this project, but I have no place to ask

I've done with disabling firewall and flushing DNS but that doesn't seem to solve my issue

**Comment by Anonym0us33** [comment]
I have a similar error upon calling 

```
voyager = Voyager(
    mc_port = 65243,
    openai_api_key=openai_api_key
)
voyager.learn()
```
It gives:

```
Mineflayer process has exited, restarting
Subprocess mineflayer started with PID 22472.
Mineflayer process has exited, restarting
\Voyager\voyager\env\process_monitor.py:65: UserWarning: Subprocess mineflayer failed to start.
  warnings.warn(f"Subprocess {self.name} failed to start.")
```

```

requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /start (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001600>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))

```

**Comment by hwigithub** [comment]
Same issue, for Azure auth, I don't see any server receiving request at 127.0.0.1.

For mc_port auth, I got an error: RuntimeError: Minecraft server reply with code 400 (I have no problem connecting to my local LAN port from another minecraft client).

**Comment by stupidstupidstupidstupid** [comment]
Same issue.

Any ideas?

**Comment by xieleo5** [comment]
Hi, all. Thanks for your interest in this project. It's normal that you got a connection refused or 404 error after you click that link. You will still see the new URL in your browser. You just need to copy and paste that link. It should contain things like `code=M.C....` in that link.

**Comment by world-DESIGNER** [comment]
Oh, I saw the connection refused and instinctively thought something was wrong, but then the following issue occurred

`Traceback (most recent call last):
  File "C:\Users\yangh\Documents\Voyager\run.py", line 12, in <module>
    voyager = Voyager(
              ^^^^^^^^
  File "C:\Users\yangh\Documents\Voyager\voyager\voyager.py", line 102, in __init__
    self.env = VoyagerEnv(
               ^^^^^^^^^^^
  File "C:\Users\yangh\Documents\Voyager\voyager\env\bridge.py", line 42, in __init__
    self.mc_instance = self.get_mc_instance()
                       ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yangh\Documents\Voyager\voyager\env\bridge.py", line 67, in get_mc_instance
    return MinecraftInstance(
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\yangh\Documents\Voyager\voyager\env\minecraft_launcher.py", line 36, in __init__
    self.mc_command = self.get_mc_command()
                      ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yangh\Documents\Voyager\voyager\env\minecraft_launcher.py", line 89, in get_mc_command
    login_data = minecraft_launcher_lib.microsoft_account.complete_login(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yangh\AppData\Local\Programs\Python\Python311\Lib\site-packages\minecraft_launcher_lib\microsoft_account.py", line 261, in complete_login
    token = token_request["access_token"]
            ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'access_token'`

**Comment by jiabin-guo** [comment]
how did you fix it?
