### ISSUE TITLE
Error: 'The model: `gpt-4` does not exist' - mc_port

### ISSUE THREAD

**Issue by UntiltledLifeProject** [MineDojo/Voyager#63]
I made it to the point where the bot joins and attempts to cut wood but it doesn't move and leaves and joins just to fail again. Well, I tried to reinstall basically anything I could to see maybe because of previous things I had to troubleshoot, but I had no luck I just keep getting this error. 

Python 3.10
Nofejs 18.16
Minecraft 1.19
Fabric 14.18

Minecraft :  none
Minefalyer: [20230603_004503.log](https://github.com/MineDojo/Voyager/files/11641889/20230603_004503.log)

![Screenshot (2)](https://github.com/MineDojo/Voyager/assets/103298208/968153a8-2e36-40d9-a6e6-aefd5a2409b4)

**Comment by theblazehen** [comment]
Does your OpenAI account have GPT-4 access?

**Comment by pbharrin** [comment]
I have a similar issue, I have ChatGPT Plus and can use GPT-4 on chat.openai.com, but I don't see it as a model choice in the playground.  Is gpt-4 API access separate from the GUI usage?

**Comment by theblazehen** [comment]
Yes, it is. You need to get on the waitlist: https://openai.com/waitlist/gpt-4-api

**Comment by UntiltledLifeProject** [comment]
I didn't know I had to do something like that! Thank you theblazehen
