### ISSUE TITLE
When running voyager.learn() nothing happens

### ISSUE THREAD

**Issue by Klyphs** [MineDojo/Voyager#68]
When I run the file to boot the AI, I sometimes see a flash of cmd, and nothing happens after. Not sure how to proceed. I have run through everything I thought could be the issue and keep hitting dead ends. I have reviewed everything in the readme, and even repeated the process twice and the problem is identical. I'm sure its something dumb, would appreciate some ideas.
...
Python v3.10, Nodejs v19.8.1, Minecraft v1.19, Fabric v0.14.18

**Comment by theblazehen** [comment]
Try opening `cmd` first, and running `python yourscript.py` from there, then you should see any errors that show up

**Comment by Klyphs** [comment]
Thank you, it seems bridge.py is running into an error because gymnasium supposedly isn't downloaded (it is). At least theres somewhere to start! Thank you
