### ISSUE TITLE
Could You Please Clarify What the `skills` Variable Represents in Voyager?

### ISSUE THREAD

**Issue by ItsBean** [MineDojo/Voyager#69]
I am seeking clarification regarding the variable `skills` derived from the line `skills = self.skill_manager.retrieve_skills(query=self.context) ` in a given piece of code. Owing to constraints related to the lack of a GPT-4 API, I am unable to debug the code independently. I am wondering whether this code segment is part of an asynchronous function or if it serves a different purpose. I kindly request your assistance in understanding this particular line of code.

**Comment by theblazehen** [comment]
FYI, if you look around on certain discords, you can get gpt-4 api access, just unofficially. I'm using https://discord.gg/9m4PGyFP

**Comment by go-maple** [comment]
I want to talk in discord.

**Comment by xieleo5** [comment]
Hi, the `skills` are just the skills that are retrieved from the learned skill library in each round. It's saved under `ckpt/skill/skills.json`.

**Comment by co1one** [comment]
> FYI, if you look around on certain discords, you can get gpt-4 api access, just unofficially. I'm using https://discord.gg/9m4PGyFP

hhhiii,i want join in the discord to discuss too,could you plz invite me to the group
