### ISSUE TITLE
Removing specific skills during training

### ISSUE THREAD

**Issue by theblazehen** [MineDojo/Voyager#72]
### Briefly describe your issue
During the learning process I notice that it repeatedly fails to handle chests correctly. Is there any way to remove just the knowledge of chests, so it can learn anew? I've tried removing it from the json, but it complains that there's a mismatch with the skill count in parquet then

**Comment by xieleo5** [comment]
Hi, could you elaborate more about how the bot failed to handle chests? I believe I add a check to not add tasks related to depositing items into the skill library.

For adding and removing tasks, I may update the README file later this week if I have time. In short, you need to regenerate the Chroma vectordb using the new `skills.json` you want to use.

**Comment by theblazehen** [comment]
Thanks for the info. I started a fresh training run, without using the skill library. The issue was indeed related to trying to deposit items into chests
