### ISSUE TITLE
ConnectionError after bot connects, leaves and reconnects

### ISSUE THREAD

**Issue by j4ix** [MineDojo/Voyager#75]
I don't know what I'm doing wrong, but this is what it's saying

"('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))"

![image](https://github.com/MineDojo/Voyager/assets/34204597/c8638769-6ccb-474d-a8bc-47e3ae2adf1a)

**Comment by xieleo5** [comment]
Hi, can you share your Mineflayer log and Minecraft log here?

**Comment by Greg-Tarr** [comment]
Mineflayer installation failed, reinstall NodeJS - make sure it's Version 16.20 from https://nodejs.org/download/release/v16.20.0/

Then follow the instructions directly. If you get a cb.apply error follow: https://stackoverflow.com/questions/63214997/typeerror-cb-apply-is-not-a-function
and run ```npm install graceful-fs --save-dev```
