### ISSUE TITLE
Documentation to enable running with a headless minecraft server

### ISSUE THREAD

**Issue by theblazehen** [MineDojo/Voyager#76]
I intend to write this documentation, will send a PR, just putting it here for tracking

**Comment by GoingMyWay** [comment]
Cool. Did you manage to run the mc_port mode with a headless MC server? There is a new discussion: https://github.com/MineDojo/Voyager/issues/88

**Comment by GoingMyWay** [comment]
> I intend to write this documentation, will send a PR, just putting it here for tracking

Hi, it is great to know that is possible to use the minecraft server to run the game. I have launched the game and put the mod files into the mods directory. However, I could not find a method to set the gamemode to peaceful and allow cheats on. Do you know how to set the configurations in the Python code and the Linux commands?
