### ISSUE TITLE
Documentation with some good seeds for training

### ISSUE THREAD

**Issue by theblazehen** [MineDojo/Voyager#77]
I find it sometimes struggles with certain biomes. I suggest a document with certain good seeds for training purposes (Mainly, avoiding water at first)

I'm currently about to kick off a training run on https://mcseeder.com/?seed=1392041844&version=1.19.2 however https://mcseeder.com/?seed=-2177513829&version=1.19.2 looks promising as well

**Comment by GoingMyWay** [comment]
Hi, what are the two links showing? How can I use the site https://mcseeder.com in Voyager training?

**Comment by egeozguroglu** [comment]
Any updates here? @xieleo5

**Comment by xieleo5** [comment]
Hi, during our experiments, we also used something like this seeder to filter some bad biomes that contain a lot of water area. I think you can further filter the seed by resources, mobs, ... My experience is that you should avoid water areas since the Mineflayer now cannot handle swimming actions well.

**Comment by egeozguroglu** [comment]
You've not linked a seeder, but I'm assuming you used something like MC Seeder -- which we've also tried. The starting biome/location of Voyager never matched the biome at (0,0,0) shown on the seeder. Voyager also doesn't start at the origin. Were you able to control the starting biome, if so how?

**Comment by xieleo5** [comment]
I think the starting point is just not (0, 0, 0). When the room owner is spawned in the game, they will be spawned at the origin. I think the first step of Voyager will move the bot to the player location, which will be the original point. I believe the seeder should be able to tell the original point.
