### ISSUE TITLE
Stop learning

### ISSUE THREAD

**Issue by Shrek616** [MineDojo/Voyager#79]
How to stop learning?

**Comment by theblazehen** [comment]
Just ^C it

**Comment by Shrek616** [comment]
> Just ^C it

Thanks, but it didn't work, it was writing an error related to the database. I fixed this with the addition this for my runvoyager.py:
voyager = Voyager(
    mc_port=25565,
    openai_api_key=openai_api_key,
    **ckpt_dir="ckpt",
    resume=True,**
)
