### ISSUE TITLE
UnicodeDecodeError: 'cp949' codec can't decode byte 0xe2 in position 1524: illegal multibyte sequence

### ISSUE THREAD

**Issue by AppStudioLB** [MineDojo/Voyager#81]
PS F:\AI Project\Voyager> pip install -e .
Obtaining file:///F:/AI%20Project/Voyager
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "F:\AI Project\Voyager\setup.py", line 38, in <module>
          long_description=_read_file("README.md"),
                           ^^^^^^^^^^^^^^^^^^^^^^^
        File "F:\AI Project\Voyager\setup.py", line 16, in _read_file
          return fp.read()
                 ^^^^^^^^^
      UnicodeDecodeError: 'cp949' codec can't decode byte 0xe2 in position 1524: illegal multibyte sequence
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

--------------------------------------------------------------------------------------------

How can I fix pip installation error? Is it the problem of utf?

**Comment by xieleo5** [comment]
Hi, can you try to pull the latest version? Someone fix the pip install problem in pull request #80

**Comment by AppStudioLB** [comment]
Yes, it works. Thank You
