### ISSUE TITLE
Should temperature typehint be `int` or `float`?

### ISSUE THREAD

**Issue by nero19960329** [MineDojo/Voyager#83]
### Briefly describe your issue
I found that temperature's typehint at `voyager/voyager.py` are `int`, but its typehint in langchain is float, which is different.

https://github.com/hwchase17/langchain/blob/master/langchain/chat_models/openai.py#LL142C5-L142C16

### Please provide your python, nodejs, Minecraft, and Fabric versions here
...
### [If applicable] Please provide the Minefalyer and Minecraft logs, you can find the log under `logs` folder
...
### [If applicable] Please provide the GPT conversations that are printed each round.
...

**Comment by xieleo5** [comment]
Sorry about this typo, it should be `float`. Fixed in the latest commit.

**Comment by yasek13** [comment]
https://github.com/MineDojo/Voyager/commit/edeee8383a22b96b54bff51c6cf809306a7b34a3
