### ISSUE TITLE
KeyError: 'access_token'

### ISSUE THREAD

**Issue by Lizzit** [MineDojo/Voyager#85]
### Briefly describe your issue
I've tryed everything on the Azure App but nothing, it still give me the KeyError: 'access_token'. I've tryed with all the platform, always using different names but same option about supported account

### Please provide your python, nodejs, Minecraft, and Fabric versions here
python: 3.11.3
nodejs: 8.19.2
Minecraft: 1.19.4
fabric: 0.14.21

**Comment by BrunoFANG1** [comment]
Hi! I think you should try mc_port instead of Azure_login. It probably has some issue with Microsoft. I did not see anyone solve this problem up until now.

**Comment by GravermanDev** [comment]
As the creator of minecraft_launcher_lib said in [here](https://codeberg.org/JakobDev/minecraft-launcher-lib/issues/80)

it's probably Microsoft's bug

**Comment by xieleo5** [comment]
Hi, just update the FAQ. If you cannot use Azure Login, please use mc_port.

**Comment by Lizzit** [comment]
I've made it run with the mcçport but i got this issue


Your last round rollout terminated due to error:
The model: `gpt-4` does not exist
Failed to complete task Mine 1 wood log. Skipping to next task.
Completed tasks:
Failed tasks: Mine 1 wood log, Mine 1 wood log, Mine 1 wood log
Starting task Mine 1 wood log for at most 4 times
Mineflayer process has exited, restarting
Subprocess mineflayer started with PID 36896.
Server started on port 3000

**Comment by KingVulpes** [comment]
> 

can someone tell me what mc_port is
