### ISSUE TITLE
how to use mc_port

### ISSUE THREAD

**Issue by IchBinsDerTimMC** [MineDojo/Voyager#86]
### Briefly describe your issue
i cant find the information for mc_port.  Azure login is obvious but i cant find the method for mc_port.

**Comment by xieleo5** [comment]
[Here](https://scholar.google.com/citations?user=bGB6wacAAAAJ&hl=en&authuser=1)

**Comment by xieleo5** [comment]
You can find it [here](https://github.com/MineDojo/Voyager/blob/main/installation/minecraft_instance_install.md#option-2-minecraft-official-launcher)

**Comment by IchBinsDerTimMC** [comment]
Yeah, i found that too but this is my code for example:
from voyager import Voyager

# You can also use mc_port instead of azure_login, but azure_login is highly recommended
azure_login = {
    "client_id": "YOUR_CLIENT_ID",
    "redirect_url": "https://127.0.0.1/auth-response",
    "secret_value": "[OPTIONAL] YOUR_SECRET_VALUE",
    "version": "fabric-loader-0.14.18-1.19", # the version Voyager is tested on
}
openai_api_key = "YOUR_API_KEY"

voyager = Voyager(
    azure_login=azure_login,
    openai_api_key=openai_api_key,
)

# start lifelong learning
voyager.learn()

if i remove the azure_login part:

from voyager import Voyager

# You can also use mc_port instead of azure_login, but azure_login is highly recommended
openai_api_key = "YOUR_API_KEY"

voyager = Voyager(
    openai_api_key=openai_api_key,
)

# start lifelong learning
voyager.learn()

after i did this he said: Either mc_port or azure_login muste be specified.
Where i can find the code base for mc_port? What i have to write in the code?

**Comment by IchBinsDerTimMC** [comment]
sorry if thats an obious question. I'm mainly not an programmer. Im just a YouTuber here in Germany who wants to show this ai. 😶

**Comment by IchBinsDerTimMC** [comment]
okey, nervermind. I got it, but now i got the error code Minecraft server reply with code 500.
![mine](https://github.com/MineDojo/Voyager/assets/135794269/309df253-eba0-433a-8f86-6acb3f1b04a2)

**Comment by IchBinsDerTimMC** [comment]
Nevermind. i got it. But now my bot just restarting. i read the FAQ and edit my code. I don't know what is wrong.
![mine2](https://github.com/MineDojo/Voyager/assets/135794269/367c7a7f-8596-49db-9465-a86e97396e35)
![mine2](https://github.com/MineDojo/Voyager/assets/135794269/e29b0bda-5aff-42e2-8b28-6603f2743808)

**Comment by GoingMyWay** [comment]
> You can find it [here](https://github.com/MineDojo/Voyager/blob/main/installation/minecraft_instance_install.md#option-2-minecraft-official-launcher)

Hi, should we install the mods suggested by the Azure login mode even run the game in mc_port mode?

**Comment by GoingMyWay** [comment]
> @GoingMyWay Hi, both method needs to install the Fabric mods. It's essential for running the experiments.

Thanks. I have already installed the required Fabric mods. @xieleo5 By the way, do you have Discord group of MineDojo and Voyager users? It would be great for users to discuss and share ideas.
