### ISSUE TITLE
Can we use the minecraft-server instead of minecraft-client?

### ISSUE THREAD

**Issue by MetaCandiru** [MineDojo/Voyager#88]
Because my server doesn't have the gui. Could the voyager run in a nogui server with minecraft-server?

**Comment by xieleo5** [comment]
Yes, Mineflayer works on a headless server theoretically. However, we didn't test it. You may need to do some investigation yourself. The key point is publishing the server to LAN and getting the mc_port. Then you can use mc_port to connect to the game and play.

**Comment by MetaCandiru** [comment]
i mean could the voyager&nbsp;interactive with minecraft-server directly?



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年6月7日(星期三) 下午5:55
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [MineDojo/Voyager] Can we use the minecraft-server instead of minecraft-client? (Issue #88)





 
Yes, Mineflayer works on a headless server theoretically. However, we didn't test it. You may need to do some investigation yourself. The key point is publishing the server to LAN and getting the mc_port. Then you can use mc_port to connect to the game and play.

**Comment by theblazehen** [comment]
Yes, it works. Will write the docs later today

**Comment by GoingMyWay** [comment]
> i mean could the voyager&nbsp;interactive with minecraft-server directly?
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2023年6月7日(星期三) 下午5:55 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [MineDojo/Voyager] Can we use the minecraft-server instead of minecraft-client? (Issue #88) Yes, Mineflayer works on a headless server theoretically. However, we didn't test it. You may need to do some investigation yourself. The key point is publishing the server to LAN and getting the mc_port. Then you can use mc_port to connect to the game and play. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

I managed to run Voyager on the server without gui. 

![image](https://github.com/MineDojo/Voyager/assets/9346460/a658a961-cf94-4511-a7cb-8b53b394f120)

**Comment by GoingMyWay** [comment]
> Yes, it works. Will write the docs later today

@theblazehen Hi, have you successfully reproduced the results with MineCraft Server? I tried many times on running the code with MineCraft server and the results were very bad.

**Comment by MetaCandiru** [comment]
How did you do it? In my understanding, the minecraft on the server side is used to connect to the client and let the client run. It directly interacts without client, and then the server runs independently?



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年6月16日(星期五) 上午9:57
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [MineDojo/Voyager] Can we use the minecraft-server instead of minecraft-client? (Issue #88)





  
i mean could the voyager&nbsp;interactive with minecraft-server directly?
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2023年6月7日(星期三) 下午5:55 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [MineDojo/Voyager] Can we use the minecraft-server instead of minecraft-client? (Issue #88) Yes, Mineflayer works on a headless server theoretically. However, we didn't test it. You may need to do some investigation yourself. The key point is publishing the server to LAN and getting the mc_port. Then you can use mc_port to connect to the game and play. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
I managed to run Voyager on the server without gui.

**Comment by theblazehen** [comment]
@GoingMyWay Yeah, it works. Check out https://github.com/MineDojo/Voyager/pull/100/files

**Comment by GoingMyWay** [comment]
> @GoingMyWay Yeah, it works. Check out https://github.com/MineDojo/Voyager/pull/100/files

Great. Thank you @theblazehen. BTW, how did you manage to set the right configurations of the server, especially the value of `spawn-protection`?

**Comment by theblazehen** [comment]
I'm not sure I understand your question @GoingMyWay ?
