### ISSUE TITLE
How to run experiment properly with mc_port?

### ISSUE THREAD

**Issue by GoingMyWay** [MineDojo/Voyager#89]
Hi, thanks for creating such an awesome repo. After setting up the environment, I ran the code with mc_port locally on my MacBook Pro. After all the iterations, the final performance is not as good as it in the paper. Could you please share some best practices on reproducing the results?

**Comment by xieleo5** [comment]
Hi, did you use the latest branch to run the experiment? What did the bot got stuck on?

**Comment by GoingMyWay** [comment]
> Hi, thanks for your interest in this project. We'd love to help and here are some questions: Did you use the latest branch to run the experiment? 

Thanks for prompt reply. I cloned the main branch and run the experiments on my MacBook Pro. 

> What did the bot got stuck on?

I actually do not know right now. I found that the bot only finished mining wood log after the game. Did you run the experiment with Azure login mode?

**Comment by xieleo5** [comment]
Hi, you need to first `git pull` to update your local codebase to the latest version. 

We have tested both Azure Login and mc_port. The key difference between these two methods is that using mc_port need you to manually resume when the process crash. The performance of the two methods is the same.

Before running the experiments, make sure you install all the Fabric mods. These mods are essential for running.

Also, after you start running, please monitor the bot's behavior for a while and make sure it succeeded to finish some tasks. Some of the missing installation steps may cause the bot to get stuck forever.

**Comment by xieleo5** [comment]
Changed the title since the issue is more about running the experiments.

**Comment by GoingMyWay** [comment]
> Hi, you need to first `git pull` to update your local codebase to the latest version.
> 
> We have tested both Azure Login and mc_port. The key difference between these two methods is that using mc_port need you to manually resume when the process crash. The performance of the two methods is the same.
> 
> Before running the experiments, make sure you install all the Fabric mods. These mods are essential for running.
> 
> Also, after you start running, please monitor the bot's behavior for a while and make sure it succeeded to finish some tasks. Some of the missing installation steps may cause the bot to get stuck forever.

Thanks for the help. I close the issue and will run the newest code.
