### ISSUE TITLE
What are "bot left the game", "bot joined the game", "server pause" and "sever unpause"?

### ISSUE THREAD

**Issue by GoingMyWay** [MineDojo/Voyager#90]
In mc_port mode, I found "bot left the game", "bot joined the game", "server pause" and "sever unpause" are shown in the game text. What are "bot left the game", "bot joined the game", "server pause" and "sever unpause"? Why is it needed to make the bot left the game and joined the again and again?

**Comment by xieleo5** [comment]
Hi, for bot left and join, you can refer to [FAQ](https://github.com/MineDojo/Voyager/blob/main/FAQ.md#i-saw-the-bot-left-and-rejoin-the-game-after-each-task)

For server pause, it's used for waiting for the GPT-4 to reply.

**Comment by GoingMyWay** [comment]
> Hi, for bot left and join, you can refer to [FAQ](https://github.com/MineDojo/Voyager/blob/main/FAQ.md#i-saw-the-bot-left-and-rejoin-the-game-after-each-task)
> 
> For server pause, it's used for waiting for the GPT-4 to reply.

Thanks!!!
