### ISSUE TITLE
The variable `max_retries` doesn't seem to work.

### ISSUE THREAD

**Issue by aeft** [MineDojo/Voyager#92]
### Briefly describe your issue
The variable `max_retries` doesn't seem to work. Maybe you missed the if condition.

Code: https://github.com/MineDojo/Voyager/blob/12025800790e16ddc9e4f61de18863859b4edf31/voyager/agents/curriculum.py#LL292C49-L292C60

![image](https://github.com/MineDojo/Voyager/assets/21154878/a75d67b6-f353-4754-9771-ca52e4674ed8)

**Comment by xieleo5** [comment]
Hi, thanks for helping us to find this issue! Fixed in the latest commit.
