### ISSUE TITLE
AI always does the same

### ISSUE THREAD

**Issue by IchBinsDerTimMC** [MineDojo/Voyager#94]
### Briefly describe your issue
The problem is that the AI does not move forward on its own. I have restarted the AI several times. Again and again it does not manage to craft a wood pickaxe. The first wood mining always works really well and also within the first 5 minutes, but after that he has only once managed to get out of the infinite loop and to craft a crafting table and then a pickaxe. But I deleted this skill again because I only tested it to see if it would run at all. After that I started my YouTube project and want to show how the whole thing works and how much you can achieve. But now it is no longer possible for me to exceed this limit of the pickaxe crafting.  Apart from the video (which is not your problem) I would like to get further. I have uploaded a pastebin here once where you can see what exactly he tried. 

For your information I use ChatGPT 3.5 Turbo. Unfortunately I don't have access to ChatGPT 4 at the moment, but I will ask my community tomorrow if someone has one. If someone here knows how I can get one / someone has one please contact me. 

### [If applicable] Please provide the GPT conversations that are printed each round.
https://pastebin.com/nZyFkWHd

**Comment by jwjohns** [comment]
i had the same issue with gpt-4 as well.

**Comment by co1one** [comment]
same here

**Comment by asimaranov** [comment]
Same
