### ISSUE TITLE
undescriptive installation guide

### ISSUE THREAD

**Issue by asheden** [MineDojo/Voyager#95]
the guide is reasonably friendly to people already used to more "programmy" endeavours and don't really know minecraft extremely well, but not the other way around. as someone who loves the game and is a huge ai enthusiast, but doesn't actually get their hands dirty often, it is very frustrating and demotivating to get *this* close to getting this incredible project running, only to be met with strange errors, not knowing if it assumes you've installed something already, or if i missed a step, or if i'm not using the right command prompt. "well, cmd worked this far, but now it's just not working anymore. this bit of code looks different from the rest. should i have put it somewhere else? i should probaby be using the python one, but that failed at step 1, so what am i doing wrong?" i get that casual minecraft players don't often go to github pages to run AI projects locally, but this is such a fantastic thing i was so happy to find out you could just run by yourself, that i couldn't help but try. i got really worried when i saw "Python Install: (BOX OF CODE)", and heartbroken when even after over an hour of trying to fix it, a handful of stackoverflow threads and tutorial posts on developer websites, i couldn't get past a single error that didn't even get a passing mention in the installation guide. there's not even a discord server or overall group where you can talk to people and ask for support, which is what led to me writing in the github issues page instead. i would deeply, truly love to make a world and play with this, but i simply don't know how. i hope we can get a more beginner-friendly guide soon, or at least a tutorial video or a discord server or something.

just in case, if anyone's willing to help, i'm aedenuniverse on discord. i would be thrilled if someone helped me with this. thanks

**Comment by GoingMyWay** [comment]
Hi, I would like to know what problems did you encounter? Could you please put the errors here?

**Comment by asheden** [comment]
it became too confusing for me to follow with all the azure stuff; i had tried skipping it but it gave me a "from is not recognized as an internal command" error. i'd love to be helped on discord if you'd like, but i also find it important to make a clearer guide in general for other folks who might run into the same troubles as me

**Comment by GoingMyWay** [comment]
> it became too confusing for me to follow with all the azure stuff; i had tried skipping it but it gave me a "from is not recognized as an internal command" error. i'd love to be helped on discord if you'd like, but i also find it important to make a clearer guide in general for other folks who might run into the same troubles as me

Now, running the code in Azure login mode is not available. Using the mc_port mode.

**Comment by 0xDREAMS** [comment]
>Using the mc_port mode.

You should add instructions on how to do that.

**Comment by 0xDREAMS** [comment]
>Using the mc_port mode.

You should add instructions on how to do that @GoingMyWay

**Comment by GoingMyWay** [comment]
> > Using the mc_port mode.
> 
> You should add instructions on how to do that @GoingMyWay
> 
> ```
> azure_login = { ... }
> voyager = Voyager(
>     azure_login=azure_login,
>     openai_api_key=openai_api_key,
> )
> ```
> 
> or
> 
> ```
> mc_port = <port provided by minecraft>
> voyager = Voyager(
>     mc_port=mc_port
>     openai_api_key=openai_api_key,
> )
> ```

Right. The example code in README is the code for the Azure login mode.
