### ISSUE TITLE
The model: `gpt-4` does not exist

### ISSUE THREAD

**Issue by AppStudioLB** [MineDojo/Voyager#96]
Render Action Agent system message with 0 control_primitives
****Action Agent human message****
Code from the last round: No code in the first round

Execution error: No error

Chat log: None

Biome: jagged_peaks

Time: day

Nearby blocks: stone, snow, snow_block, spruce_leaves

Nearby entities (nearest to farthest): None

Health: 20.0/20

Hunger: 20.0/20

Position: x=-47.5, y=109.0, z=0.5

Equipment: [None, None, None, None, None, None]

Inventory (0/36): Empty

Chests: None

Task: Mine 1 wood log

Context: You can mine one of oak, birch, spruce, jungle, acacia, dark oak, or mangrove logs.

Critique: None

Mineflayer process has exited, restarting
Subprocess mineflayer started with PID 16444.
Server started on port 3000

Your last round rollout terminated due to error:
The model: `gpt-4` does not exist
Failed to complete task Mine 1 wood log. Skipping to next task.
Completed tasks:
Failed tasks: Mine 1 wood log, Mine 1 wood log
Starting task Mine 1 wood log for at most 4 times

------------------------------------------------------------------------------

How can I fix this problem? If the issue is that I am not on the waitlist for GPT-4, how can I utilize GPT-3.5 instead?

**Comment by UntiltledLifeProject** [comment]
This means you do not have access to chat gpt-4 API. You have to request access to it on Open Ai. if you want to use 3.5 you have to find the Voyager/voyager/voyager.py in the voyager.py txt doc you can change the few places that say gpt-4 with "gpt-3.5-turbo"  but don't forget to change  skill_manager_retrieval_top_k: int = 5 to  skill_manager_retrieval_top_k: int = 2. This is due to the limitations of gpt 3.5. One more thing log into the open Ai stuff and sign up for the "pay as you go" thing because if you don't you will be limited and the bot won't work. it also takes 48 hours to fully be able to use it too :/  I think that's all it's how I got mine to run but TBH it sucks and I'm waiting for gpt-4 API

**Comment by GoingMyWay** [comment]
> This means you do not have access to chat gpt-4 API. You have to request access to it on Open Ai. if you want to use 3.5 you have to find the Voyager/voyager/voyager.py in the voyager.py txt doc you can change the few places that say gpt-4 with "gpt-3.5-turbo" but don't forget to change skill_manager_retrieval_top_k: int = 5 to skill_manager_retrieval_top_k: int = 2. This is due to the limitations of gpt 3.5. One more thing log into the open Ai stuff and sign up for the "pay as you go" thing because if you don't you will be limited and the bot won't work. it also takes 48 hours to fully be able to use it too :/ I think that's all it's how I got mine to run but TBH it sucks and I'm waiting for gpt-4 API

Hi, have you managed to reproduce the results of the paper with GPT-3.5 or GPT-4?

**Comment by GoingMyWay** [comment]
> > > This means you do not have access to chat gpt-4 API. You have to request access to it on Open Ai. if you want to use 3.5 you have to find the Voyager/voyager/voyager.py in the voyager.py txt doc you can change the few places that say gpt-4 with "gpt-3.5-turbo" but don't forget to change skill_manager_retrieval_top_k: int = 5 to skill_manager_retrieval_top_k: int = 2. This is due to the limitations of gpt 3.5. One more thing log into the open Ai stuff and sign up for the "pay as you go" thing because if you don't you will be limited and the bot won't work. it also takes 48 hours to fully be able to use it too :/ I think that's all it's how I got mine to run but TBH it sucks and I'm waiting for gpt-4 API
> > 
> > 
> > Hi, have you managed to reproduce the results of the paper with GPT-3.5 or GPT-4?
> 
> GPT-3.5 turbo. But it's nowhere as good as gpt-4 so I'd say not to the full potential of the paper

@UntiltledLifeProject , Sounds the results are not bad. What are the completed tasks? Until now, I can only run the code to complete the following tasks with GPT-4:

```
["Mine 1 wood log", "Find a forest biome and mine 10 wood logs", "Mine 10 oak logs", "Craft a wooden pickaxe", "Mine 10 cobblestone", "Craft a stone axe and a stone sword", "Craft a stone pickaxe", "Craft an oak pickaxe", "Craft a wooden hoe"]
```
```

**Comment by UntiltledLifeProject** [comment]
> > > > This means you do not have access to chat gpt-4 API. You have to request access to it on Open Ai. if you want to use 3.5 you have to find the Voyager/voyager/voyager.py in the voyager.py txt doc you can change the few places that say gpt-4 with "gpt-3.5-turbo" but don't forget to change skill_manager_retrieval_top_k: int = 5 to skill_manager_retrieval_top_k: int = 2. This is due to the limitations of gpt 3.5. One more thing log into the open Ai stuff and sign up for the "pay as you go" thing because if you don't you will be limited and the bot won't work. it also takes 48 hours to fully be able to use it too :/ I think that's all it's how I got mine to run but TBH it sucks and I'm waiting for gpt-4 API
> > > 
> > > 
> > > Hi, have you managed to reproduce the results of the paper with GPT-3.5 or GPT-4?
> > 
> > 
> > GPT-3.5 turbo. But it's nowhere as good as gpt-4 so I'd say not to the full potential of the paper
> 
> @UntiltledLifeProject , Sounds the results are not bad. What are the completed tasks? Until now, I can only run the code to complete the following tasks with GPT-4:
> 
> ```
> ["Mine 1 wood log", "Find a forest biome and mine 10 wood logs", "Mine 10 oak logs", "Craft a wooden pickaxe", "Mine 10 cobblestone", "Craft a stone axe and a stone sword", "Craft a stone pickaxe", "Craft an oak pickaxe", "Craft a wooden hoe"]
> ```
sorry I was busy for the last few days. As you may already know Open AI had updated so I set the code to run "gpt-3.5-turbo-16k-0613" it was slow but i ran the bot all night and this is what it did and failed to do "Failed to complete task Gather seashells from the beach. Skipping to next task.
Completed tasks: Mine 1 wood log, Craft 4 wooden planks, Mine 3 oak logs, Craft a wooden pickaxe, Mine 8 stone blocks, Craft a stone pickaxe, Mine 10 iron ore, Smelt 10 iron ore into iron ingots, Craft an iron pickaxe and craft 16 wooden planks, Mine 3 birch logs, Craft a crafting table, Craft a stone axe, Mine 3 oak logs and open and check the items inside the unknown chests, Open and check the items inside the chest Mine 10 deepslate blocks, Mine 5 deepslate iron ore, Smelt the deepslate iron ore into iron ingots, Explore the forest biome and gather oak logs and birch logs, Craft 4 oak logs into oak planks, Explore the forest biome and gather birch logs, Craft a set of torches using the oak logs and sticks from your inventory, Craft a wooden sword using oak planks, Kill the pig to obtain raw porkchop, Continue exploring the forest biome and gather more resources Look for flowers, tall grass, and mushrooms, Gather seagrass from the water and collect sand and gravel from the beach, Dive underwater and explore for underwater ruins or shipwrecks, Equip the cobblestone in your inventory, Craft a glass block using the sand in your inventory, Harvest the sugar cane and craft paper, Craft 3 paper using the sugar cane in your inventory, Explore the beach biome and gather more sand and sugar cane, Craft a fishing rod using sticks and string from your inventory, then go fishing to catch some fish, Open and check the items inside the unknown chest, Open and check the items inside the chest, Kill the cod in the water to obtain raw fish, Explore the beach biome and gather more resources, Gather oak saplings and birch saplings from the forest biome, Kill the squid in the water to obtain ink sacs, Gather more sand from the beach, Craft glass blocks using the sand in your inventory
Failed tasks: Mine 5 copper ore, Smelt 35 iron ore into iron ingots, Open and check the items inside the unknown chests, Craft a set of iron armor, Mine 10 deepslate blocks, Mine 7 more deepslate blocks, Craft an iron sword, Collect oak saplings and birch saplings, Craft a wooden shovel using oak planks, Mine 10 coal ore, Cook the raw porkchop to obtain a cooked porkchop, Eat a cooked porkchop from your inventory to replenish your health Then, continue exploring the forest biome and gather more resources, such as flowers, tall grass, and mushrooms, Gather seashells from the beach, Gather seashells from the beach, Gather seashells from the beach, Explore the beach biome and gather seashells, Gather seashells from the beach, Dive underwater and search for coral, Eat a cooked porkchop from your inventory to replenish your health, Explore the forest biome and gather more oak logs, birch logs, flowers, tall grass, and mushrooms, Dive underwater and search for underwater ruins or shipwrecks Gather any valuable items you find, Gather seashells from the beach"
