### ISSUE TITLE
Bot joins, dies, changes game rules, leaves, accomplishes nothing

### ISSUE THREAD

**Issue by 0xDREAMS** [MineDojo/Voyager#97]
![image](https://github.com/MineDojo/Voyager/assets/90912741/0be59075-d115-41b2-8831-8a0a0bbadc4c)

**Comment by GoingMyWay** [comment]
Similar issue. Bot left the game and never joins the game, resulting the programme getting stuck.

**Comment by egeozguroglu** [comment]
@0xDREAMS How were you able to visualize the GUI of the game, while running Voyager?

**Comment by xieleo5** [comment]
Hi, @egeozguroglu  I think the GUI will always pop up when you run the experiments. You can then enter spectator mod to see the bot's view.
